// apps/frontend/src/views/system/menu/index.vue
<template>
  <div class="p-4">
    <NCard class="mb-4">
      <NForm inline :model="searchForm" label-placement="left" size="small">
        <NFormItem label="菜单名称" path="permName">
          <NInput v-model:value="searchForm.permName" placeholder="输入菜单名称" />
        </NFormItem>
        <NFormItem label="状态" path="status">
          <DictSelect dictCode="BASE_STATUS" v-model:value="searchForm.status" class="w-48!" />
        </NFormItem>
        <NFormItem>
          <div class="flex gap-2">
            <NButton type="primary" @click="handleSearch">
              <template #icon>
                <AppIcon icon="antd:SearchOutlined" />
              </template>
              查询
            </NButton>
            <NButton @click="handleReset">
              <template #icon>
                <AppIcon icon="antd:ReloadOutlined" />
              </template>
              重置
            </NButton>
          </div>
        </NFormItem>
      </NForm>
    </NCard>

    <NCard>
      <div class="flex justify-between items-center mb-4">
        <NSpace>
          <NButton type="primary" size="small" @click="openDialog()" v-permission="['MENU_ADD']">
            <template #icon>
              <AppIcon icon="antd:PlusOutlined" />
            </template>
            新增菜单
          </NButton>
        </NSpace>
      </div>

      <NDataTable
        size="small"
        :columns="columns"
        :data="menuTree"
        :loading="isLoading"
        :row-key="(row) => row.id"
        children-key="children"
        default-expand-all
      />
    </NCard>

    <MenuDialog ref="dialogRef" @success="refetch" />
    <ButtonManageDialog ref="buttonManageDialogRef" @success="refetch" />
  </div>
</template>

<script setup lang="ts">
import { ref, h, reactive, computed } from 'vue'
import { useQuery, useMutation } from '@pinia/colada'
import { getMenuList, deleteMenu, type Menu } from '@/api/menu'
import MenuDialog from './MenuDialog.vue'
import ButtonManageDialog from './ButtonManageDialog.vue'
import { useDialog, useMessage } from 'naive-ui'
import DictTag from '@/components/Dict/DictTag.vue'
import {
  NCard,
  NForm,
  NFormItem,
  NInput,
  NButton,
  NDataTable,
  type DataTableColumns,
} from 'naive-ui'
import DynamicIcon from '@/components/Icon/DynamicIcon.vue'
import { renderIcon } from '@/layouts/composables/useMenu'
import { usePermission } from '@/composables/usePermission'

defineOptions({
  name: 'SystemMenu',
})

const dialog = useDialog()
const message = useMessage()
const { hasPermission } = usePermission()

const dialogRef = ref()
const buttonManageDialogRef = ref()

const searchForm = reactive({
  permName: '',
  status: null as number | null,
})
const createQueryState = () => ({
  permName: searchForm.permName || undefined,
  status: searchForm.status || undefined,
})
const queryState = ref(createQueryState())

const { data, isLoading, refetch } = useQuery({
  key: () => ['menus', queryState.value],
  query: () => getMenuList(queryState.value),
})

const menuTree = computed<Menu[]>(() => data.value?.data || [])

const deleteMutation = useMutation({
  mutation: (id: number) => deleteMenu(id),
  onSuccess: () => {
    message.success('Menu deleted')
    refetch()
  },
})

const columns: DataTableColumns<Menu> = [
  {
    title: '菜单名称',
    key: 'permName',
    render(row) {
      return row.menuType === 'divider' ? h('span', null, '分割线') : row.permName
    },
  },
  {
    title: '图标',
    key: 'icon',
    render(row) {
      return row.icon ? renderIcon(row.icon)!() : null
    },
  },
  { title: '权限编码', key: 'permCode' },
  { title: '路径', key: 'path' },
  {
    title: '菜单类型',
    key: 'menuType',
    render(row) {
      return h(DictTag, { value: row.menuType, dictCode: 'MENU_TYPE' })
    },
  },
  {
    title: '状态',
    key: 'status',
    render(row) {
      return h(DictTag, { value: row.status, dictCode: 'BASE_STATUS' })
    },
  },
  { title: '排序', key: 'sort', width: 80 },
  {
    title: '操作',
    key: 'actions',
    width: 240,
    render(row) {
      const actions = []

      if (hasPermission('MENU_BUTTON') && (row.menuType === 'page' || row.menuType === 'window')) {
        actions.push(
          h(
            NButton,
            {
              type: 'warning',
              text: true,
              size: 'small',
              title: '按钮管理',
              onClick: () => openButtonManageDialog(row),
            },
            { icon: () => h(DynamicIcon, { icon: 'antd:AppstoreOutlined' }) },
          ),
        )
      }

      if (hasPermission('MENU_ADD') && row.resourceType !== 'button') {
        actions.push(
          h(
            NButton,
            {
              type: 'info',
              text: true,
              size: 'small',
              onClick: () => openDialog(undefined, row.id),
              title: 'Add Child',
            },
            { icon: () => h(DynamicIcon, { icon: 'antd:PlusOutlined' }) },
          ),
        )
      }

      if (hasPermission('MENU_EDIT')) {
        actions.push(
          h(
            NButton,
            {
              type: 'success',
              text: true,
              size: 'small',
              onClick: () => openDialog(row.id),
            },
            { icon: () => h(DynamicIcon, { icon: 'antd:EditOutlined' }) },
          ),
        )
      }

      if (hasPermission('MENU_DELETE')) {
        actions.push(
          h(
            NButton,
            {
              type: 'error',
              text: true,
              size: 'small',
              onClick: () => confirmDelete(row),
            },
            { icon: () => h(DynamicIcon, { icon: 'antd:DeleteOutlined' }) },
          ),
        )
      }

      return h('div', { class: 'flex gap-2' }, actions)
    },
  },
]

const handleSearch = () => {
  queryState.value = createQueryState()
}

const handleReset = () => {
  searchForm.permName = ''
  searchForm.status = null
  queryState.value = createQueryState()
}

const openDialog = (id?: number, parentId?: number) => {
  dialogRef.value?.open(id, parentId)
}

const openButtonManageDialog = (menu: Menu) => {
  buttonManageDialogRef.value?.open(menu.id, menu.permName)
}

const confirmDelete = (menu: Menu) => {
  dialog.warning({
    title: 'Confirm Delete',
    content: `Are you sure you want to delete "${menu.permName}"?`,
    positiveText: 'Delete',
    negativeText: 'Cancel',
    onPositiveClick: () => {
      deleteMutation.mutate(menu.id)
    },
  })
}
</script>

// apps/react-admin/src/pages/system/menu/index.tsx
import { useMemo, useState } from 'react'
import { useMutation, useQuery } from '@tanstack/react-query'
import { App, Button, Card, Form, Input, Popconfirm, Space, Table } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import {
  DeleteOutlined,
  EditOutlined,
  PlusOutlined,
  ReloadOutlined,
  SearchOutlined,
  AppstoreOutlined,
} from '@ant-design/icons'
import { deleteMenu, getMenuList, type Menu } from '@/api/menu'
import { DictSelect } from '@/components/dict/DictSelect'
import { DictTag } from '@/components/dict/DictTag'
import { DynamicIcon } from '@/components/DynamicIcon'
import { PermissionGate } from '@/components/PermissionGate'
import { ButtonManageDialog } from '@/components/system/menu/ButtonManageDialog'
import { MenuDialog } from '@/components/system/menu/MenuDialog'
import { queryClient } from '@/lib/query-client'

export function MenuPage() {
  const { message } = App.useApp()
  const [form] = Form.useForm<{ permName?: string; status?: number | null }>()
  const [query, setQuery] = useState<{ permName?: string; status?: number | undefined }>({})
  const [dialogOpen, setDialogOpen] = useState(false)
  const [editingMenuId, setEditingMenuId] = useState<number | null>(null)
  const [parentId, setParentId] = useState<number | null>(null)
  const [buttonDialog, setButtonDialog] = useState<{
    open: boolean
    id: number | null
    name: string
  }>({
    open: false,
    id: null,
    name: '',
  })

  const { data = [], isLoading } = useQuery({
    queryKey: ['menus', query],
    queryFn: () => getMenuList(query),
  })

  const deleteMutation = useMutation({
    mutationFn: deleteMenu,
    onSuccess: async () => {
      message.success('菜单删除成功')
      await queryClient.invalidateQueries({ queryKey: ['menus'] })
    },
  })

  const columns = useMemo<ColumnsType<Menu>>(
    () => [
      {
        title: '菜单名称',
        dataIndex: 'permName',
        key: 'permName',
        render: (value: string, record) => (record.menuType === 'divider' ? '分割线' : value),
      },
      {
        title: '图标',
        dataIndex: 'icon',
        key: 'icon',
        width: 80,
        render: (value: string | undefined) =>
          value ? <DynamicIcon icon={value} className="size-4" /> : null,
      },
      { title: '权限编码', dataIndex: 'permCode', key: 'permCode', width: 180 },
      { title: '路径', dataIndex: 'path', key: 'path', width: 180 },
      {
        title: '菜单类型',
        dataIndex: 'menuType',
        key: 'menuType',
        width: 110,
        render: (value: string) => <DictTag value={value} dictCode="MENU_TYPE" />,
      },
      {
        title: '状态',
        dataIndex: 'status',
        key: 'status',
        width: 100,
        render: (value: number) => <DictTag value={value} dictCode="BASE_STATUS" />,
      },
      { title: '排序', dataIndex: 'sort', key: 'sort', width: 80 },
      {
        title: '操作',
        key: 'actions',
        width: 260,
        render: (_, record) => (
          <Space size={4}>
            <PermissionGate permCode="MENU_BUTTON">
              {record.menuType === 'page' || record.menuType === 'window' ? (
                <Button
                  type="text"
                  size="small"
                  icon={<AppstoreOutlined />}
                  onClick={() => {
                    setButtonDialog({
                      open: true,
                      id: record.id,
                      name: record.permName,
                    })
                  }}
                />
              ) : null}
            </PermissionGate>
            <PermissionGate permCode="MENU_ADD">
              {record.resourceType !== 'button' ? (
                <Button
                  type="text"
                  size="small"
                  icon={<PlusOutlined />}
                  onClick={() => {
                    setEditingMenuId(null)
                    setParentId(record.id)
                    setDialogOpen(true)
                  }}
                />
              ) : null}
            </PermissionGate>
            <PermissionGate permCode="MENU_EDIT">
              <Button
                type="text"
                size="small"
                icon={<EditOutlined />}
                onClick={() => {
                  setEditingMenuId(record.id)
                  setParentId(null)
                  setDialogOpen(true)
                }}
              />
            </PermissionGate>
            <PermissionGate permCode="MENU_DELETE">
              <Popconfirm
                title="确认删除菜单"
                description={`确定删除“${record.permName}”吗？`}
                okText="删除"
                cancelText="取消"
                onConfirm={() => {
                  void deleteMutation.mutateAsync(record.id)
                }}
              >
                <Button danger type="text" size="small" icon={<DeleteOutlined />} />
              </Popconfirm>
            </PermissionGate>
          </Space>
        ),
      },
    ],
    [deleteMutation],
  )

  return (
    <Space direction="vertical" size={16} style={{ display: 'flex' }}>
      <Card>
        <Form form={form} layout="inline" initialValues={{ permName: '', status: null }}>
          <Form.Item label="菜单名称" name="permName">
            <Input allowClear placeholder="输入菜单名称" style={{ width: 180 }} />
          </Form.Item>
          <Form.Item label="状态" name="status">
            <DictSelect dictCode="BASE_STATUS" style={{ width: 180 }} />
          </Form.Item>
          <Form.Item>
            <Space>
              <Button
                type="primary"
                icon={<SearchOutlined />}
                onClick={() => {
                  const values = form.getFieldsValue()
                  setQuery({
                    permName: values.permName?.trim() || undefined,
                    status: values.status ?? undefined,
                  })
                }}
              >
                查询
              </Button>
              <Button
                icon={<ReloadOutlined />}
                onClick={() => {
                  form.resetFields()
                  setQuery({})
                }}
              >
                重置
              </Button>
            </Space>
          </Form.Item>
        </Form>
      </Card>

      <Card>
        <Space direction="vertical" size={16} style={{ display: 'flex' }}>
          <PermissionGate permCode="MENU_ADD">
            <Button
              type="primary"
              icon={<PlusOutlined />}
              onClick={() => {
                setEditingMenuId(null)
                setParentId(null)
                setDialogOpen(true)
              }}
            >
              新增菜单
            </Button>
          </PermissionGate>

          <Table<Menu>
            rowKey="id"
            loading={isLoading}
            columns={columns}
            dataSource={data}
            pagination={false}
            expandable={{ defaultExpandAllRows: true }}
          />
        </Space>
      </Card>

      <MenuDialog
        open={dialogOpen}
        menuId={editingMenuId}
        parentId={parentId}
        onClose={() => {
          setDialogOpen(false)
          setEditingMenuId(null)
          setParentId(null)
        }}
      />
      <ButtonManageDialog
        open={buttonDialog.open}
        menuId={buttonDialog.id}
        menuName={buttonDialog.name}
        onClose={() => {
          setButtonDialog({
            open: false,
            id: null,
            name: '',
          })
        }}
      />
    </Space>
  )
}
