// apps/frontend/src/views/system/role/RolePermissionDialog.vue
<template>
  <NModal
    :show="show"
    :title="dialogTitle"
    preset="card"
    class="w-full md:w-180!"
    @update:show="close"
  >
    <NSpin :show="loading">
      <NTree
        class="max-h-110 overflow-auto border border-gray-200 rounded p-3"
        :data="menuTree"
        checkable
        block-line
        default-expand-all
        key-field="id"
        label-field="permName"
        children-field="children"
        :render-label="renderTreeLabel"
        :checked-keys="checkedKeys"
        @update:checked-keys="handleCheckedKeysChange"
      />
    </NSpin>

    <template #footer>
      <div class="flex justify-end gap-2">
        <NButton @click="close">取消</NButton>
        <NButton type="primary" :loading="submitting" @click="handleSave">保存</NButton>
      </div>
    </template>
  </NModal>
</template>

<script setup lang="ts">
import { computed, h, ref } from 'vue'
import { NModal, NButton, NTree, NSpin, NTag, useMessage, type TreeOption } from 'naive-ui'
import { getMenuAndButtonPermissions, type PermissionTreeNode } from '@/api/permission'
import { assignRolePermissions, getRolePermissions } from '@/api/role'

const emit = defineEmits<{
  (e: 'success'): void
}>()

const message = useMessage()

const show = ref(false)
const loading = ref(false)
const submitting = ref(false)
const roleId = ref<number>()
const roleName = ref('')
const menuTree = ref<TreeOption[]>([])
const checkedKeys = ref<number[]>([])

const dialogTitle = computed(() =>
  roleName.value ? `分配菜单权限 - ${roleName.value}` : '分配菜单权限',
)

const normalizeMenuTree = (nodes: PermissionTreeNode[] = []): TreeOption[] => {
  return nodes.map((node) => ({
    id: node.id,
    permName: node.permName,
    resourceType: node.resourceType,
    menuType: node.menuType,
    children: normalizeMenuTree(node.children || []),
  }))
}

const renderTreeLabel = ({ option }: { option: TreeOption }) => {
  const isButton = option.resourceType === 'button'
  const menuType = String(option.menuType || '')
  const menuTypeLabelMap: Record<string, string> = {
    menu: '菜单夹',
    page: '页面',
    link: '外链',
    iframe: '内嵌',
    window: '新窗口',
    divider: '分割线',
    group: '分组',
  }
  const menuTypeTagTypeMap: Record<string, 'default' | 'primary' | 'info' | 'success' | 'warning' | 'error'> = {
    menu: 'success',
    page: 'info',
    link: 'primary',
    iframe: 'warning',
    window: 'primary',
    divider: 'default',
    group: 'success',
  }
  const menuTypeLabel = menuTypeLabelMap[menuType]
  const menuTypeTagType = menuTypeTagTypeMap[menuType] || 'default'

  return h('div', { class: 'flex items-center gap-2' }, [
    h('span', null, String(option.permName || '')),
    isButton
      ? h(
          NTag,
          { size: 'small', type: 'warning', bordered: false },
          { default: () => '按钮' },
        )
      : menuTypeLabel
        ? h(
            NTag,
            { size: 'small', type: menuTypeTagType, bordered: false },
            { default: () => menuTypeLabel },
          )
        : null,
  ])
}

const handleCheckedKeysChange = (keys: Array<string | number>) => {
  checkedKeys.value = keys.map((key) => Number(key))
}

const open = async (id: number, name?: string) => {
  roleId.value = id
  roleName.value = name || ''
  show.value = true
  loading.value = true

  try {
    const [permissionTreeRes, permissionRes] = await Promise.all([
      getMenuAndButtonPermissions({}),
      getRolePermissions(id),
    ])

    menuTree.value = normalizeMenuTree(permissionTreeRes.data || [])
    checkedKeys.value = ((permissionRes.data || []).map((item) => item.permissionId) as number[]).filter(
      (permissionId, index, list) => list.indexOf(permissionId) === index,
    )
  } catch (error) {
    console.error(error)
    message.error('加载角色权限失败')
  } finally {
    loading.value = false
  }
}

const handleSave = async () => {
  if (!roleId.value) return
  if (checkedKeys.value.length === 0) {
    message.warning('请至少选择一个菜单权限')
    return
  }

  submitting.value = true
  try {
    await assignRolePermissions(roleId.value, checkedKeys.value)
    message.success('菜单权限分配成功')
    emit('success')
    close()
  } catch (error) {
    console.error(error)
  } finally {
    submitting.value = false
  }
}

const close = () => {
  show.value = false
}

defineExpose({
  open,
  close,
})
</script>

// apps/react-admin/src/components/system/role/RolePermissionDialog.tsx
import { useEffect, useMemo, useState } from 'react'
import { useMutation, useQuery } from '@tanstack/react-query'
import { App, Modal, Spin, Tag, Tree } from 'antd'
import type { TreeDataNode } from 'antd'
import { assignRolePermissions, getRolePermissions } from '@/api/role'
import { getMenuAndButtonPermissions, type PermissionTreeNode } from '@/api/permission'
import { queryClient } from '@/lib/query-client'

type Props = {
  open: boolean
  roleId?: number | null
  roleName?: string
  onClose: () => void
}

type PermissionTreeDataNode = TreeDataNode & {
  resourceType?: PermissionTreeNode['resourceType']
  menuType?: PermissionTreeNode['menuType']
}

function getMenuTypeLabel(menuType?: PermissionTreeNode['menuType']) {
  const labelMap: Record<string, string> = {
    menu: '菜单夹',
    page: '页面',
    link: '外链',
    iframe: '内嵌',
    window: '新窗口',
    divider: '分割线',
    group: '分组',
  }
  return menuType ? labelMap[menuType] || menuType : ''
}

function normalizeTree(nodes: PermissionTreeNode[] = []): PermissionTreeDataNode[] {
  return nodes.map((node) => ({
    key: node.id,
    title: node.permName,
    resourceType: node.resourceType,
    menuType: node.menuType,
    children: normalizeTree(node.children || []),
  }))
}

export function RolePermissionDialog({ open, roleId, roleName, onClose }: Props) {
  const { message } = App.useApp()
  const [checkedKeys, setCheckedKeys] = useState<React.Key[]>([])

  const { data, isFetching } = useQuery({
    queryKey: ['role-permission-dialog', roleId],
    queryFn: async () => {
      const [tree, relations] = await Promise.all([
        getMenuAndButtonPermissions({}),
        getRolePermissions(roleId!),
      ])

      return {
        tree,
        checked: Array.from(new Set(relations.map((item) => item.permissionId))),
      }
    },
    enabled: open && Boolean(roleId),
  })

  useEffect(() => {
    if (!open) {
      setCheckedKeys([])
      return
    }

    if (data) {
      setCheckedKeys(data.checked)
    }
  }, [data, open])

  const saveMutation = useMutation({
    mutationFn: async () =>
      assignRolePermissions(
        roleId!,
        checkedKeys.map((key) => Number(key)),
      ),
    onSuccess: async () => {
      message.success('菜单权限分配成功')
      await queryClient.invalidateQueries({ queryKey: ['roles'] })
      await queryClient.invalidateQueries({ queryKey: ['auth-bootstrap'] })
      onClose()
    },
  })

  const treeData = useMemo(() => normalizeTree(data?.tree || []), [data?.tree])

  return (
    <Modal
      open={open}
      title={roleName ? `分配菜单权限 - ${roleName}` : '分配菜单权限'}
      width={760}
      okText="保存"
      cancelText="取消"
      confirmLoading={saveMutation.isPending}
      onCancel={onClose}
      onOk={() => {
        if (!checkedKeys.length) {
          message.warning('请至少选择一个菜单权限')
          return
        }

        void saveMutation.mutateAsync()
      }}
      destroyOnHidden
    >
      <Spin spinning={isFetching}>
        <div className="max-h-130 overflow-auto rounded-md border border-slate-200 p-3">
          <Tree
            checkable
            blockNode
            defaultExpandAll
            checkedKeys={checkedKeys}
            treeData={treeData}
            onCheck={(keys) => {
              setCheckedKeys(Array.isArray(keys) ? keys : keys.checked)
            }}
            titleRender={(node) => {
              const permissionNode = node as PermissionTreeDataNode
              const menuTypeLabel = getMenuTypeLabel(permissionNode.menuType)

              return (
                <div className="flex items-center gap-2">
                  <span>{String(node.title)}</span>
                  {permissionNode.resourceType === 'button' ? (
                    <Tag color="orange">按钮</Tag>
                  ) : menuTypeLabel ? (
                    <Tag color="blue">{menuTypeLabel}</Tag>
                  ) : null}
                </div>
              )
            }}
          />
        </div>
      </Spin>
    </Modal>
  )
}
