// apps/frontend/src/views/system/dictionary/components/DictionaryItemDrawer.vue
<script setup lang="ts">
import { ref, h, computed } from 'vue'
import { useQuery, useMutation } from '@pinia/colada'
import { type DictionaryItem, getDictionaryItemList, deleteDictionaryItem } from '@/api/dictionary'
import { usePermission } from '@/composables/usePermission'
import { useDialog, useMessage, type DataTableColumns } from 'naive-ui'
import { NDrawer, NDrawerContent, NButton, NDataTable, NSpace } from 'naive-ui'
import DictTag from '@/components/Dict/DictTag.vue'
import DynamicIcon from '@/components/Icon/DynamicIcon.vue'
import DictionaryItemDialog from './DictionaryItemDialog.vue'

const message = useMessage()
const dialog = useDialog()
const { hasPermission } = usePermission()

const show = ref(false)
const currentDictId = ref<number>()

const columns: DataTableColumns<DictionaryItem> = [
  { title: '标签', key: 'label', sorter: 'default' },
  { title: '值', key: 'value', sorter: 'default' },
  { title: '颜色类型', key: 'colorType', sorter: 'default' },
  { title: '排序', key: 'sort', sorter: 'default' },
  {
    title: '状态',
    key: 'status',
    render(row) {
      return h(DictTag, { value: row.status, dictCode: 'BASE_STATUS' })
    },
  },
  {
    title: '操作',
    key: 'actions',
    render(row) {
      const actions = []

      if (hasPermission('DICT_EDIT')) {
        actions.push(
          h(
            NButton,
            {
              size: 'small',
              circle: true,
              quaternary: true,
              onClick: () => editItem(row),
            },
            { icon: () => h(DynamicIcon, { icon: 'antd:EditOutlined' }) },
          ),
        )
      }

      if (hasPermission('DICT_DELETE')) {
        actions.push(
          h(
            NButton,
            {
              size: 'small',
              circle: true,
              quaternary: true,
              type: 'error',
              onClick: () => confirmDeleteItem(row),
            },
            { icon: () => h(DynamicIcon, { icon: 'antd:DeleteOutlined' }) },
          ),
        )
      }

      return h('div', { class: 'flex gap-2' }, actions)
    },
  },
]

const { data, isLoading, refetch } = useQuery({
  key: ['dictItems', () => currentDictId.value],
  query: () => getDictionaryItemList(currentDictId.value!),
  enabled: () => !!show.value && !!currentDictId.value,
})

const items = computed(() => data.value?.data || [])

const deleteMutation = useMutation({
  mutation: (id: number) => deleteDictionaryItem(id),
  onSuccess: () => {
    message.success('删除成功')
    refetch()
  },
})

const open = (dictId: number) => {
  currentDictId.value = dictId
  show.value = true
}

const close = () => {
  show.value = false
}

const confirmDeleteItem = (item: DictionaryItem) => {
  dialog.warning({
    title: '确认删除',
    content: `确定要删除字典项 "${item.label}" 吗？`,
    positiveText: '删除',
    negativeText: '取消',
    onPositiveClick: () => {
      deleteMutation.mutate(item.id)
    },
  })
}

const itemDialogRef = ref()

const handleItemSuccess = () => {
  refetch()
}

const openNew = () => {
  itemDialogRef.value?.open(undefined, currentDictId.value)
}

const editItem = (item: DictionaryItem) => {
  itemDialogRef.value?.open(item)
}

const getRowKey = (row: DictionaryItem) => row.id

defineExpose({
  open,
  close,
})
</script>

<template>
  <NDrawer :show="show" @update:show="close" width="800" placement="right">
    <NDrawerContent title="字典项列表">
      <template #header>
        <div class="flex justify-between items-center w-full">
          <NSpace>
            <NButton
              v-if="hasPermission('DICT_ADD')"
              type="primary"
              size="small"
              @click="openNew"
            >
              <template #icon>
                <AppIcon icon="antd:PlusOutlined" />
              </template>
              新增字典项
            </NButton>
          </NSpace>
        </div>
      </template>

      <NDataTable
        :columns="columns"
        :data="items"
        :loading="isLoading"
        :row-key="getRowKey"
        size="small"
      />
    </NDrawerContent>
  </NDrawer>

  <DictionaryItemDialog ref="itemDialogRef" @success="handleItemSuccess" />
</template>

// apps/react-admin/src/components/system/dictionary/DictionaryItemDrawer.tsx
import { useMemo, useState } from 'react'
import { useMutation, useQuery } from '@tanstack/react-query'
import { App, Button, Drawer, Popconfirm, Space, Table, Tag, Typography } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { DeleteOutlined, EditOutlined, PlusOutlined } from '@ant-design/icons'
import {
  createDictionaryItem,
  deleteDictionaryItem,
  getDictionaryItemList,
  updateDictionaryItem,
  type DictionaryItem,
} from '@/api/dictionary'
import { DictTag } from '@/components/dict/DictTag'
import { PermissionGate } from '@/components/PermissionGate'
import { queryClient } from '@/lib/query-client'
import { DictionaryItemDialog } from '@/components/system/dictionary/DictionaryItemDialog'

type Props = {
  open: boolean
  dictTypeId?: number | null
  dictName?: string
  onClose: () => void
}

export function DictionaryItemDrawer({ open, dictTypeId, dictName, onClose }: Props) {
  const { message } = App.useApp()
  const [editingItem, setEditingItem] = useState<Partial<DictionaryItem> | null>(null)

  const { data = [], isLoading } = useQuery({
    queryKey: ['dict-items', dictTypeId],
    queryFn: () => getDictionaryItemList(dictTypeId!),
    enabled: open && Boolean(dictTypeId),
  })

  const refresh = async () => {
    await queryClient.invalidateQueries({ queryKey: ['dict-items', dictTypeId] })
  }

  const saveMutation = useMutation({
    mutationFn: async (values: Partial<DictionaryItem>) => {
      const payload = {
        ...values,
        dictTypeId: dictTypeId ?? undefined,
      }

      if (editingItem?.id) {
        return updateDictionaryItem({ ...payload, id: editingItem.id })
      }

      return createDictionaryItem(payload)
    },
    onSuccess: async () => {
      message.success(editingItem?.id ? '字典项更新成功' : '字典项创建成功')
      await refresh()
    },
  })

  const deleteMutation = useMutation({
    mutationFn: deleteDictionaryItem,
    onSuccess: async () => {
      message.success('字典项删除成功')
      await refresh()
    },
  })

  const columns = useMemo<ColumnsType<DictionaryItem>>(
    () => [
      { title: '标签', dataIndex: 'label', key: 'label' },
      { title: '值', dataIndex: 'value', key: 'value' },
      {
        title: '颜色类型',
        dataIndex: 'colorType',
        key: 'colorType',
        render: (value: string) => value ? <Tag>{value}</Tag> : '-',
      },
      { title: '排序', dataIndex: 'sort', key: 'sort', width: 90 },
      {
        title: '状态',
        dataIndex: 'status',
        key: 'status',
        width: 100,
        render: (value: number) => <DictTag value={value} dictCode="BASE_STATUS" />,
      },
      {
        title: '操作',
        key: 'actions',
        width: 120,
        render: (_, record) => (
          <Space size={4}>
            <PermissionGate permCode="DICT_EDIT">
              <Button type="text" size="small" icon={<EditOutlined />} onClick={() => setEditingItem(record)} />
            </PermissionGate>
            <PermissionGate permCode="DICT_DELETE">
              <Popconfirm
                title="确认删除字典项"
                description={`确定删除“${record.label}”吗？`}
                okText="删除"
                cancelText="取消"
                onConfirm={() => {
                  void deleteMutation.mutateAsync(record.id)
                }}
              >
                <Button danger type="text" size="small" icon={<DeleteOutlined />} />
              </Popconfirm>
            </PermissionGate>
          </Space>
        ),
      },
    ],
    [deleteMutation],
  )

  return (
    <>
      <Drawer
        open={open}
        width={860}
        title={dictName ? `${dictName} - 字典项` : '字典项列表'}
        onClose={onClose}
      >
        <Space direction="vertical" size={16} style={{ display: 'flex' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <Typography.Text type="secondary">管理当前字典下的所有字典项</Typography.Text>
            <PermissionGate permCode="DICT_ADD">
              <Button type="primary" icon={<PlusOutlined />} onClick={() => setEditingItem({ dictTypeId: dictTypeId ?? undefined, status: 1, sort: 0 })}>
                新增字典项
              </Button>
            </PermissionGate>
          </div>

          <Table<DictionaryItem> rowKey="id" loading={isLoading} columns={columns} dataSource={data} pagination={false} />
        </Space>
      </Drawer>
      <DictionaryItemDialog
        open={Boolean(editingItem)}
        initialValues={editingItem}
        onClose={() => setEditingItem(null)}
        onSubmit={async (values) => {
          await saveMutation.mutateAsync(values)
        }}
      />
    </>
  )
}
