// apps/react-admin/src/pages/system/user/index.tsx
import { useMemo, useState } from 'react'
import { useMutation, useQuery } from '@tanstack/react-query'
import {
  App,
  Button,
  Card,
  Form,
  Input,
  Popconfirm,
  Space,
  Table,
  Tag,
  TreeSelect,
  Typography,
} from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { DeleteOutlined, EditOutlined, PlusOutlined, ReloadOutlined, SearchOutlined } from '@ant-design/icons'
import { deleteUser, getUserList, type User } from '@/api/user'
import { getDeptTree, type Dept } from '@/api/dept'
import { PermissionGate } from '@/components/PermissionGate'
import { UserDialog } from '@/components/system/user/UserDialog'
import { queryClient } from '@/lib/query-client'

type SearchFormValues = {
  username?: string
  mobile?: string
  deptId?: number | null
}

export function UserPage() {
  const { message } = App.useApp()
  const [form] = Form.useForm<SearchFormValues>()
  const [query, setQuery] = useState({
    username: '',
    mobile: '',
    deptId: null as number | null,
    pageNo: 1,
    pageSize: 10,
  })
  const [dialogOpen, setDialogOpen] = useState(false)
  const [editingUserId, setEditingUserId] = useState<number | null>(null)

  const { data: deptOptions = [] } = useQuery({
    queryKey: ['dept-tree'],
    queryFn: getDeptTree,
  })

  const { data, isLoading, isFetching } = useQuery({
    queryKey: ['system-users', query],
    queryFn: () => getUserList(query),
  })

  const deleteMutation = useMutation({
    mutationFn: deleteUser,
    onSuccess: async () => {
      message.success('用户已删除')
      await queryClient.invalidateQueries({ queryKey: ['system-users'] })
    },
  })
  const { mutateAsync: deleteUserAsync, isPending: isDeleting } = deleteMutation

  const treeData = useMemo(
    () =>
      deptOptions.map(function mapDept(node: Dept): { title: string; value: number; key: number; children?: ReturnType<typeof mapDept>[] } {
        return {
          title: node.name,
          value: node.id,
          key: node.id,
          children: node.children?.map(mapDept),
        }
      }),
    [deptOptions],
  )

  const columns = useMemo<ColumnsType<User>>(
    () => [
      { title: 'ID', dataIndex: 'id', key: 'id', width: 88 },
      { title: '用户名', dataIndex: 'username', key: 'username', width: 140 },
      { title: '昵称', dataIndex: 'nickname', key: 'nickname', width: 140 },
      {
        title: '部门',
        key: 'dept',
        width: 140,
        render: (_, record) => record.dept?.name || '-',
      },
      {
        title: '岗位',
        key: 'post',
        width: 140,
        render: (_, record) => record.post?.postName || '-',
      },
      { title: '邮箱', dataIndex: 'email', key: 'email', width: 180, render: (value: string | undefined) => value || '-' },
      { title: '手机号', dataIndex: 'mobile', key: 'mobile', width: 140, render: (value: string | undefined) => value || '-' },
      {
        title: '状态',
        dataIndex: 'status',
        key: 'status',
        width: 100,
        render: (value: number) => (
          <Tag color={value === 1 ? 'green' : 'default'}>
            {value === 1 ? '启用' : '禁用'}
          </Tag>
        ),
      },
      {
        title: '角色',
        key: 'roles',
        width: 220,
        render: (_, record) => {
          if (!record.roles?.length) {
            return '-'
          }

          return (
            <Space wrap size={[4, 4]}>
              {record.roles.map((role) => (
                <Tag key={role.id} color="blue">
                  {role.roleName}
                </Tag>
              ))}
            </Space>
          )
        },
      },
      {
        title: '创建时间',
        dataIndex: 'createdAt',
        key: 'createdAt',
        width: 180,
        render: (value: string | undefined) => value || '-',
      },
      {
        title: '操作',
        key: 'actions',
        fixed: 'right',
        width: 140,
        render: (_, record) => (
          <Space size={4}>
            <PermissionGate permCode="USER_EDIT">
                  <Button
                    type="text"
                    size="small"
                    icon={<EditOutlined />}
                    onClick={() => {
                      setEditingUserId(record.id)
                      setDialogOpen(true)
                    }}
                  />
                </PermissionGate>
            <PermissionGate permCode="USER_DELETE">
                  <Popconfirm
                title="确认删除用户"
                description={`确定删除用户“${record.username}”吗？`}
                okText="删除"
                cancelText="取消"
                onConfirm={() => {
                  void deleteUserAsync(record.id)
                }}
              >
                <Button
                  danger
                  type="text"
                  size="small"
                  icon={<DeleteOutlined />}
                  loading={isDeleting}
                />
              </Popconfirm>
            </PermissionGate>
          </Space>
        ),
      },
    ],
    [deleteUserAsync, isDeleting],
  )

  const handleSearch = () => {
    const values = form.getFieldsValue()
    setQuery((current) => ({
      ...current,
      username: values.username?.trim() || '',
      mobile: values.mobile?.trim() || '',
      deptId: values.deptId ?? null,
      pageNo: 1,
    }))
  }

  const handleReset = () => {
    form.resetFields()
    setQuery({
      username: '',
      mobile: '',
      deptId: null,
      pageNo: 1,
      pageSize: 10,
    })
  }

  return (
    <Space direction="vertical" size={16} style={{ display: 'flex' }}>
      <Card>
        <Form
          form={form}
          layout="inline"
          initialValues={{
            username: '',
            mobile: '',
            deptId: null,
          }}
        >
          <Form.Item label="用户名" name="username">
            <Input allowClear placeholder="输入用户名" style={{ width: 180 }} />
          </Form.Item>
          <Form.Item label="手机号" name="mobile">
            <Input allowClear placeholder="输入手机号" style={{ width: 180 }} />
          </Form.Item>
          <Form.Item label="部门" name="deptId">
            <TreeSelect
              allowClear
              placeholder="选择部门"
              style={{ width: 200 }}
              treeData={treeData}
              treeDefaultExpandAll
            />
          </Form.Item>
          <Form.Item>
            <Space>
              <Button type="primary" icon={<SearchOutlined />} onClick={handleSearch}>
                查询
              </Button>
              <Button icon={<ReloadOutlined />} onClick={handleReset}>
                重置
              </Button>
            </Space>
          </Form.Item>
        </Form>
      </Card>

      <Card>
        <Space direction="vertical" size={16} style={{ display: 'flex' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <Space>
              <Typography.Title level={5} style={{ margin: 0 }}>
                用户管理
              </Typography.Title>
              {isFetching ? <Typography.Text type="secondary">刷新中...</Typography.Text> : null}
            </Space>
            <PermissionGate permCode="USER_ADD">
              <Button
                type="primary"
                icon={<PlusOutlined />}
                onClick={() => {
                  setEditingUserId(null)
                  setDialogOpen(true)
                }}
              >
                新增用户
              </Button>
            </PermissionGate>
          </div>

          <Table<User>
            rowKey="id"
            loading={isLoading}
            columns={columns}
            dataSource={data?.list ?? []}
            scroll={{ x: 1440 }}
            pagination={{
              current: query.pageNo,
              pageSize: query.pageSize,
              total: data?.total ?? 0,
              showSizeChanger: true,
              pageSizeOptions: [10, 20, 30],
              showTotal: (total) => `共 ${total} 条`,
              onChange: (page, pageSize) => {
                setQuery((current) => ({
                  ...current,
                  pageNo: page,
                  pageSize,
                }))
              },
            }}
          />
        </Space>
      </Card>
      <UserDialog
        open={dialogOpen}
        userId={editingUserId}
        onClose={() => {
          setDialogOpen(false)
          setEditingUserId(null)
        }}
      />
    </Space>
  )
}

// apps/frontend/src/views/system/user/index.vue
<template>
  <div class="p-4">
    <NCard class="mb-4">
      <NForm inline :model="searchForm" label-placement="left" size="small">
        <NFormItem label="用户名" path="username">
          <NInput v-model:value="searchForm.username" placeholder="输入用户名" />
        </NFormItem>
        <NFormItem label="手机号" path="mobile">
          <NInput v-model:value="searchForm.mobile" placeholder="输入手机号" />
        </NFormItem>
        <NFormItem label="部门" path="deptId">
          <NTreeSelect
            v-model:value="searchForm.deptId"
            :options="deptOptions"
            placeholder="选择部门"
            clearable
            key-field="id"
            label-field="name"
            children-field="children"
            style="width: 180px"
          />
        </NFormItem>
        <NFormItem>
          <div class="flex gap-2">
            <NButton type="primary" @click="handleSearch">
              <template #icon>
                <AppIcon icon="antd:SearchOutlined" />
              </template>
              查询
            </NButton>
            <NButton @click="handleReset">
              <template #icon>
                <AppIcon icon="antd:ReloadOutlined" />
              </template>
              重置
            </NButton>
          </div>
        </NFormItem>
      </NForm>
    </NCard>

    <NCard>
      <div class="flex justify-between items-center mb-4">
        <n-space>
          <NButton type="primary" size="small" @click="openDialog()" v-permission="['USER_ADD']">
            <template #icon>
              <AppIcon icon="antd:PlusOutlined" />
            </template>
            新增用户
          </NButton>
        </n-space>
      </div>

      <NDataTable
        :columns="columns"
        :data="userList"
        :loading="isLoading"
        :pagination="pagination"
        remote
        :row-key="(row) => row.id"
      />
    </NCard>

    <UserDialog ref="dialogRef" @success="refetch" />
  </div>
</template>

<script setup lang="ts">
import { ref, h, reactive, computed } from 'vue'
import { useQuery, useMutation } from '@pinia/colada'
import { getUserList, deleteUser, type User, type UserSearchParams } from '@/api/user'
import { getDeptTree } from '@/api/dept'
import UserDialog from './UserDialog.vue'
import { useDialog, useMessage } from 'naive-ui'
import {
  NCard,
  NForm,
  NFormItem,
  NInput,
  NTreeSelect,
  NButton,
  NDataTable,
  NTag,
  type DataTableColumns,
  type PaginationProps,
} from 'naive-ui'
import DictTag from '@/components/Dict/DictTag.vue'
import DynamicIcon from '@/components/Icon/DynamicIcon.vue'
import type { Dept } from '@/api/dept'
import { usePermission } from '@/composables/usePermission'

defineOptions({
  name: 'SystemUser',
})

const dialog = useDialog()
const message = useMessage()
const { hasPermission } = usePermission()

const dialogRef = ref()
const deptOptions = ref<Dept[]>([])

const searchForm = reactive<UserSearchParams>({
  username: '',
  mobile: '',
  deptId: null,
  pageNo: 1,
  pageSize: 10,
})
const createQueryState = () => ({
  username: searchForm.username,
  mobile: searchForm.mobile,
  deptId: searchForm.deptId,
  pageNo: searchForm.pageNo ?? 1,
  pageSize: searchForm.pageSize ?? 10,
})
const queryState = ref(createQueryState())

const fetchDeptTree = async () => {
  try {
    const res = await getDeptTree()
    deptOptions.value = res.data || []
  } catch (e) {
    console.error(e)
  }
}

// Fetch department tree on mount
fetchDeptTree()

const { data, isLoading, refetch } = useQuery({
  key: () => ['users', queryState.value],
  query: () => getUserList(queryState.value),
})

const userList = computed(() => data.value?.data.list || [])
const total = computed(() => data.value?.data.total || 0)

const deleteMutation = useMutation({
  mutation: (id: number) => deleteUser(id),
  onSuccess: () => {
    message.success('User deleted')
    refetch()
  },
})

const pagination = reactive<PaginationProps>({
  page: 1,
  pageSize: 10,
  get itemCount() {
    return total.value
  },
  showSizePicker: true,
  pageSizes: [10, 20, 30],
  prefix: ({ itemCount }) => `Total ${itemCount} items`,
  onChange: (page: number) => {
    pagination.page = page
    searchForm.pageNo = page
    queryState.value = createQueryState()
  },
  onUpdatePageSize: (pageSize: number) => {
    pagination.pageSize = pageSize
    pagination.page = 1
    searchForm.pageSize = pageSize
    searchForm.pageNo = 1
    queryState.value = createQueryState()
  },
})

const columns: DataTableColumns<User> = [
  { title: 'ID', key: 'id', width: 80 },
  { title: '用户名', key: 'username' },
  { title: '昵称', key: 'nickname' },
  {
    title: '部门',
    key: 'dept',
    render(row) {
      return row.dept?.name || '-'
    },
  },
  {
    title: '岗位',
    key: 'post',
    render(row) {
      return row.post?.postName || '-'
    },
  },
  { title: '邮箱', key: 'email' },
  { title: '手机号', key: 'mobile' },
  {
    title: '状态',
    key: 'status',
    render(row) {
      return h(DictTag, { value: row.status, dictCode: 'BASE_STATUS' })
    },
  },
  {
    title: '角色',
    key: 'roles',
    render(row) {
      if (!row.roles || row.roles.length === 0) return '-'
      return h(
        'div',
        { class: 'flex gap-1 flex-wrap' },
        row.roles.map((role) =>
          h(NTag, { type: 'info', size: 'small' }, { default: () => role.roleName }),
        ),
      )
    },
  },
  { title: '创建时间', key: 'createdAt' },
  {
    title: '操作',
    key: 'actions',
    width: 150,
    render(row) {
      const actions = []

      if (hasPermission('USER_EDIT')) {
        actions.push(
          h(
            NButton,
            {
              type: 'success',
              text: true,
              size: 'small',
              onClick: () => openDialog(row.id),
            },
            { icon: () => h(DynamicIcon, { icon: 'antd:EditOutlined' }) },
          ),
        )
      }

      if (hasPermission('USER_DELETE')) {
        actions.push(
          h(
            NButton,
            {
              type: 'error',
              text: true,
              size: 'small',
              onClick: () => confirmDelete(row),
            },
            { icon: () => h(DynamicIcon, { icon: 'antd:DeleteOutlined' }) },
          ),
        )
      }

      return h('div', { class: 'flex gap-2' }, actions)
    },
  },
]

const handleSearch = () => {
  searchForm.pageNo = 1
  pagination.page = 1
  queryState.value = createQueryState()
}

const handleReset = () => {
  searchForm.username = ''
  searchForm.mobile = ''
  searchForm.deptId = null
  searchForm.pageNo = 1
  searchForm.pageSize = 10
  pagination.page = 1
  pagination.pageSize = 10
  queryState.value = createQueryState()
}

const openDialog = (id?: number) => {
  dialogRef.value?.open(id)
}

const confirmDelete = (user: User) => {
  dialog.warning({
    title: 'Confirm Delete',
    content: `Are you sure you want to delete user "${user.username}"?`,
    positiveText: 'Delete',
    negativeText: 'Cancel',
    onPositiveClick: () => {
      deleteMutation.mutate(user.id)
    },
  })
}
</script>
