// apps/frontend/src/views/system/dept/DeptDialog.vue
<template>
  <NModal
    :show="show"
    :title="isEdit ? '修改部门' : '创建部门'"
    preset="card"
    class="w-full md:w-250!"
    @update:show="close"
  >
    <NForm
      ref="formRef"
      :model="formModel"
      :rules="rules"
      label-placement="left"
      label-width="100"
      require-mark-placement="right-hanging"
    >
      <NFormItem label="上级部门" path="parentId">
        <NTreeSelect
          v-model:value="formModel.parentId"
          :options="deptTreeOptions"
          placeholder="选择上级部门（不选则为顶级部门）"
          clearable
          key-field="id"
          label-field="name"
          children-field="children"
        />
      </NFormItem>

      <NFormItem label="部门名称" path="name">
        <NInput v-model:value="formModel.name" placeholder="输入部门名称" />
      </NFormItem>

      <NFormItem label="负责人" path="leaderId">
        <NSelect
          v-model:value="formModel.leaderId"
          :options="userOptions"
          placeholder="选择负责人"
          clearable
          filterable
          label-field="label"
          value-field="value"
        />
      </NFormItem>

      <NFormItem label="显示排序" path="sort">
        <NInputNumber
          v-model:value="formModel.sort"
          placeholder="输入排序号"
          :min="0"
          class="w-full"
        />
      </NFormItem>

      <NFormItem label="部门状态" path="status">
        <DictSelect dict-code="BASE_STATUS" v-model:value="formModel.status" />
      </NFormItem>

      <NFormItem label="备注" path="remark">
        <NInput
          v-model:value="formModel.remark"
          type="textarea"
          placeholder="输入备注信息"
          :rows="3"
        />
      </NFormItem>
    </NForm>

    <template #footer>
      <div class="flex justify-end gap-2">
        <NButton @click="close">取消</NButton>
        <NButton type="primary" :loading="loading" @click="handleSave">确认</NButton>
      </div>
    </template>
  </NModal>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import {
  NModal,
  NForm,
  NFormItem,
  NInput,
  NInputNumber,
  NSelect,
  NTreeSelect,
  NButton,
  type FormInst,
  type FormRules,
} from 'naive-ui'
import { createDept, updateDept, getDeptDetail, type DeptFormData } from '@/api/dept'
import { getDeptTree, type Dept } from '@/api/dept'
import { getAllUsers, type User } from '@/api/user'
import { useMessage } from 'naive-ui'

const emit = defineEmits<{
  (e: 'success'): void
}>()

const message = useMessage()
const loading = ref(false)
const show = ref(false)
const currentId = ref<number>()
const formRef = ref<FormInst | null>(null)
const deptTreeOptions = ref<Dept[]>([])
const userOptions = ref<{ label: string; value: number }[]>([])
const isEdit = computed(() => !!currentId.value)
const initialFormModel = (): DeptFormData => ({
  name: '',
  parentId: null,
  leaderId: null,
  status: 1,
  sort: 0,
  remark: '',
})

const formModel = ref<DeptFormData>(initialFormModel())

const rules = computed<FormRules>(() => {
  return {
    name: [{ required: true, message: '部门名称不能为空', trigger: 'blur' }],
  }
})

const fetchDeptTree = async () => {
  try {
    const res = await getDeptTree()
    deptTreeOptions.value = res.data || []
  } catch (e) {
    console.error(e)
  }
}

const fetchUsers = async () => {
  try {
    const res = await getAllUsers()
    if (res.data) {
      userOptions.value = res.data.map((user: User) => ({
        label: `${user.nickname} (${user.username})`,
        value: user.id,
      }))
    }
  } catch (e) {
    console.error(e)
  }
}

const open = async (id?: number, parentId?: number | null) => {
  currentId.value = id
  show.value = true

  await fetchDeptTree()
  await fetchUsers()

  if (id) {
    loading.value = true
    try {
      const res = await getDeptDetail(id)
      const data = res.data
      formModel.value = {
        name: data.name,
        parentId: data.parentId || null,
        leaderId: data.leaderId || null,
        status: data.status,
        sort: data.sort,
        remark: data.remark || '',
      }
    } catch (error) {
      console.error(error)
      message.error('获取部门详情失败')
      close()
    } finally {
      loading.value = false
    }
  } else {
    formModel.value = {
      ...initialFormModel(),
      parentId: parentId ?? null,
    }
  }
}

const handleSave = () => {
  formRef.value?.validate(async (errors) => {
    if (!errors) {
      loading.value = true
      try {
        if (isEdit.value) {
          await updateDept(currentId.value!, formModel.value)
          message.success('更新成功')
        } else {
          await createDept(formModel.value)
          message.success('创建成功')
        }
        emit('success')
        close()
      } catch (error: unknown) {
        console.error(error)
        if (typeof error === 'object' && error !== null && 'response' in error) {
          const response = error.response as { data?: { message?: string } } | undefined
          message.error(response?.data?.message || '操作失败')
        } else {
          message.error('操作失败')
        }
      } finally {
        loading.value = false
      }
    }
  })
}

const close = () => {
  show.value = false
}

defineExpose({
  open,
  close,
})
</script>

// apps/react-admin/src/components/system/dept/DeptDialog.tsx
import { useEffect } from 'react'
import { useMutation, useQuery } from '@tanstack/react-query'
import { App, Form, Input, InputNumber, Modal, Select, TreeSelect } from 'antd'
import type { TreeSelectProps } from 'antd'
import { createDept, getDeptDetail, getDeptTree, updateDept, type Dept, type DeptFormData } from '@/api/dept'
import { getAllUsers } from '@/api/user'
import { DictSelect } from '@/components/dict/DictSelect'
import { queryClient } from '@/lib/query-client'

type Props = {
  open: boolean
  deptId?: number | null
  parentId?: number | null
  onClose: () => void
}

function mapDeptTree(nodes: Dept[]): TreeSelectProps['treeData'] {
  return nodes.map((node) => ({
    title: node.name,
    value: node.id,
    key: node.id,
    children: node.children?.length ? mapDeptTree(node.children) : undefined,
  }))
}

export function DeptDialog({ open, deptId, parentId, onClose }: Props) {
  const { message } = App.useApp()
  const [form] = Form.useForm<DeptFormData>()
  const isEdit = Boolean(deptId)

  const { data: deptTree = [] } = useQuery({
    queryKey: ['dept-tree'],
    queryFn: getDeptTree,
    enabled: open,
  })

  const { data: users = [] } = useQuery({
    queryKey: ['all-users'],
    queryFn: getAllUsers,
    enabled: open,
  })

  const { data: detail, isFetching } = useQuery({
    queryKey: ['dept-detail', deptId],
    queryFn: () => getDeptDetail(deptId!),
    enabled: open && isEdit,
  })

  useEffect(() => {
    if (!open) {
      form.resetFields()
      return
    }

    if (isEdit && detail) {
      form.setFieldsValue({
        name: detail.name,
        parentId: detail.parentId || null,
        leaderId: detail.leaderId || null,
        status: detail.status,
        sort: detail.sort,
        remark: detail.remark || '',
      })
      return
    }

    form.setFieldsValue({
      name: '',
      parentId: parentId ?? null,
      leaderId: null,
      status: 1,
      sort: 0,
      remark: '',
    })
  }, [detail, form, isEdit, open, parentId])

  const saveMutation = useMutation({
    mutationFn: async (values: DeptFormData) => {
      if (isEdit) {
        return updateDept(deptId!, values)
      }
      return createDept(values)
    },
    onSuccess: async () => {
      message.success(isEdit ? '部门更新成功' : '部门创建成功')
      await queryClient.invalidateQueries({ queryKey: ['dept-tree'] })
      onClose()
    },
    onError: (error: unknown) => {
      if (typeof error === 'object' && error !== null && 'response' in error) {
        const response = error.response as { data?: { message?: string } } | undefined
        message.error(response?.data?.message || '操作失败')
        return
      }
      message.error('操作失败')
    },
  })

  return (
    <Modal
      open={open}
      forceRender
      title={isEdit ? '修改部门' : '创建部门'}
      okText="确认"
      cancelText="取消"
      confirmLoading={saveMutation.isPending}
      onCancel={onClose}
      onOk={() => {
        void form.validateFields().then((values) => saveMutation.mutate(values))
      }}
      destroyOnHidden
    >
      <Form form={form} layout="vertical" disabled={saveMutation.isPending || isFetching}>
        <Form.Item label="上级部门" name="parentId">
          <TreeSelect
            allowClear
            treeDefaultExpandAll
            placeholder="选择上级部门"
            treeData={mapDeptTree(deptTree) ?? []}
          />
        </Form.Item>
        <Form.Item label="部门名称" name="name" rules={[{ required: true, message: '请输入部门名称' }]}>
          <Input placeholder="输入部门名称" />
        </Form.Item>
        <Form.Item label="负责人" name="leaderId">
          <Select
            allowClear
            showSearch
            placeholder="选择负责人"
            options={users.map((user) => ({
              label: `${user.nickname} (${user.username})`,
              value: user.id,
            }))}
            optionFilterProp="label"
          />
        </Form.Item>
        <Form.Item label="显示排序" name="sort">
          <InputNumber style={{ width: '100%' }} min={0} placeholder="输入排序" />
        </Form.Item>
        <Form.Item label="部门状态" name="status">
          <DictSelect dictCode="BASE_STATUS" />
        </Form.Item>
        <Form.Item label="备注" name="remark">
          <Input.TextArea rows={3} placeholder="输入备注信息" />
        </Form.Item>
      </Form>
    </Modal>
  )
}
