// apps/react-admin/src/components/system/timer/TimerLogsDrawer.tsx
import { useEffect, useMemo, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Button, Drawer, Empty, Select, Space, Spin, Tag } from 'antd'
import { ReloadOutlined, SearchOutlined } from '@ant-design/icons'
import { getTimerLogs } from '@/api/timer'

type Props = {
  open: boolean
  timerId?: number | null
  timerName?: string
  onClose: () => void
}

function formatDateTime(value?: string) {
  if (!value) return '-'
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return value
  return new Intl.DateTimeFormat('zh-CN', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: false,
  }).format(date)
}

function formatDuration(ms?: number) {
  if (!ms) return '-'
  if (ms < 1000) return `${ms}ms`
  if (ms < 60000) return `${(ms / 1000).toFixed(2)}s`
  const mins = Math.floor(ms / 60000)
  const secs = Math.round((ms % 60000) / 1000)
  return `${mins}m ${secs}s`
}

export function TimerLogsDrawer({ open, timerId, timerName, onClose }: Props) {
  const [statusFilter, setStatusFilter] = useState<number | undefined>(undefined)

  const {
    data = [],
    isFetching,
    refetch,
  } = useQuery({
    queryKey: ['timer-logs', timerId],
    queryFn: () => getTimerLogs(timerId!, 100),
    enabled: open && Boolean(timerId),
  })

  useEffect(() => {
    if (!open) {
      setStatusFilter(undefined)
    }
  }, [open])

  const filteredLogs = useMemo(
    () => (statusFilter === undefined ? data : data.filter((item) => item.status === statusFilter)),
    [data, statusFilter],
  )

  return (
    <Drawer
      open={open}
      width={860}
      title={timerName ? `${timerName} - 执行日志` : '执行日志'}
      onClose={onClose}
    >
      <Space direction="vertical" size={16} style={{ display: 'flex' }}>
        <div className="rounded-md border border-slate-200 bg-white p-3">
          <Space>
            <span>状态:</span>
            <Select
              allowClear
              size="small"
              style={{ width: 120 }}
              placeholder="全部"
              value={statusFilter}
              options={[
                { label: '成功', value: 1 },
                { label: '失败', value: 0 },
              ]}
              onChange={(value) => setStatusFilter(value)}
            />
            <Button size="small" type="primary" icon={<SearchOutlined />}>
              查询
            </Button>
            <Button size="small" icon={<ReloadOutlined />} onClick={() => void refetch()}>
              刷新
            </Button>
          </Space>
        </div>

        <Spin spinning={isFetching}>
          {filteredLogs.length === 0 ? (
            <Empty description="暂无执行日志" />
          ) : (
            <div className="max-h-[calc(100vh-300px)] overflow-y-auto">
              {filteredLogs.map((log) => (
                <div
                  key={log.id}
                  className={`mb-3 rounded-lg border-l-4 p-3 ${
                    log.status === 1
                      ? 'border-l-emerald-500 bg-emerald-50/50'
                      : 'border-l-rose-500 bg-rose-50/50'
                  }`}
                >
                  <div className="mb-2 flex items-center gap-2">
                    <Tag color={log.status === 1 ? 'success' : 'error'}>
                      {log.status === 1 ? '成功' : '失败'}
                    </Tag>
                    <span className="text-sm text-slate-600">{formatDateTime(log.startAt)}</span>
                    <span className="text-xs text-slate-500">
                      耗时: {formatDuration(log.duration)}
                    </span>
                  </div>
                  {log.result ? (
                    <pre className="overflow-x-auto rounded bg-slate-950 p-3 text-xs text-slate-100">
                      {log.result}
                    </pre>
                  ) : null}
                </div>
              ))}
            </div>
          )}
        </Spin>
      </Space>
    </Drawer>
  )
}

// apps/frontend/src/views/system/timer/TimerLogsDrawer.vue
<template>
  <NDrawer :show="show" :width="800" placement="right" @update:show="handleShowUpdate">
    <NDrawerContent :title="`${currentTimerName || ''} - 执行日志`" closable>
      <!-- 过滤器 -->
      <NCard size="small" class="mb-4">
        <NSpace align="center">
          <span>状态:</span>
          <NSelect
            v-model:value="statusFilter"
            :options="statusOptions"
            size="small"
            style="width: 120px"
            clearable
            @update:value="handleRefresh"
          />
          <NButton size="small" type="primary" @click="handleRefresh">
            <template #icon>
              <AppIcon icon="antd:SearchOutlined" />
            </template>
            查询
          </NButton>
          <NButton size="small" @click="handleRefresh">
            <template #icon>
              <AppIcon icon="antd:ReloadOutlined" />
            </template>
            刷新
          </NButton>
        </NSpace>
      </NCard>

      <!-- 日志列表 -->
      <NSpin :show="loading">
        <NEmpty v-if="filteredLogs.length === 0 && !loading" description="暂无执行日志" />
        <div v-else class="logs-container">
          <div
            v-for="log in filteredLogs"
            :key="log.id"
            class="log-item"
            :class="{ 'log-item-success': log.status === 1, 'log-item-error': log.status === 0 }"
          >
            <div class="log-item-header">
              <NSpace align="center">
                <NTag :type="log.status === 1 ? 'success' : 'error'" size="small">
                  {{ log.status === 1 ? '成功' : '失败' }}
                </NTag>
                <span class="text-sm text-gray-600">
                  <AppIcon icon="antd:ClockCircleOutlined" class="mr-1" />
                  {{ formatTime(log.startAt) }}
                </span>
                <span v-if="log.duration" class="text-xs text-gray-500">
                  耗时: {{ formatDuration(log.duration) }}
                </span>
              </NSpace>
            </div>
            <div v-if="log.result" class="log-item-result">
              <NCode :code="log.result" language="json" :word-wrap="true" />
            </div>
          </div>
        </div>
      </NSpin>

      <template #footer>
        <div class="flex justify-between text-sm text-gray-500">
          <span>共 {{ filteredLogs.length }} 条记录</span>
          <span v-if="hasMoreLogs" class="text-blue-500 cursor-pointer" @click="loadMore">
            加载更多
          </span>
        </div>
      </template>
    </NDrawerContent>
  </NDrawer>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import {
  NDrawer,
  NDrawerContent,
  NCard,
  NSpace,
  NButton,
  NSelect,
  NSpin,
  NEmpty,
  NTag,
  NCode,
} from 'naive-ui'
import { getTimerLogs, type TimerExecutionLog } from '@/api/timer'

const show = ref(false)
const currentTimerId = ref<number>()
const currentTimerName = ref<string>()
const loading = ref(false)
const logs = ref<TimerExecutionLog[]>([])
const statusFilter = ref<number | null>(null)

const statusOptions = [
  { label: '成功', value: 1 },
  { label: '失败', value: 0 },
]

const filteredLogs = computed(() => {
  if (statusFilter.value === null) {
    return logs.value
  }
  return logs.value.filter((log) => log.status === statusFilter.value)
})

const hasMoreLogs = computed(() => {
  return logs.value.length >= 50
})

const formatTime = (dateStr: string) => {
  const date = new Date(dateStr)
  return date.toLocaleString('zh-CN', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  })
}

const formatDuration = (ms: number) => {
  if (ms < 1000) {
    return `${ms}ms`
  } else if (ms < 60000) {
    return `${(ms / 1000).toFixed(2)}s`
  } else {
    const mins = Math.floor(ms / 60000)
    const secs = ((ms % 60000) / 1000).toFixed(0)
    return `${mins}m ${secs}s`
  }
}

const loadLogs = async () => {
  if (!currentTimerId.value) return

  loading.value = true
  try {
    const res = await getTimerLogs(currentTimerId.value, 100)
    logs.value = res.data || []
  } catch (error) {
    console.error('Failed to load logs:', error)
    logs.value = []
  } finally {
    loading.value = false
  }
}

const open = (timerId: number, timerName: string) => {
  currentTimerId.value = timerId
  currentTimerName.value = timerName
  show.value = true
  loadLogs()
}

const handleRefresh = () => {
  loadLogs()
}

const handleShowUpdate = (value: boolean) => {
  if (!value) {
    show.value = false
    currentTimerId.value = undefined
    currentTimerName.value = undefined
    statusFilter.value = null
    logs.value = []
  }
}

const loadMore = () => {
  // 后续可以实现分页加载更多
}

const close = () => {
  show.value = false
}

defineExpose({
  open,
  close,
  loadLogs,
})
</script>

<style scoped>
.logs-container {
  max-height: calc(100vh - 300px);
  overflow-y: auto;
}

.log-item {
  padding: 12px;
  margin-bottom: 12px;
  border-radius: 8px;
  border-left: 4px solid;
  background-color: var(--n-color-modal);
  transition: all 0.2s;
}

.log-item:hover {
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}

.log-item-success {
  border-left-color: #52c41a;
}

.log-item-error {
  border-left-color: #ff4d4f;
}

.log-item-header {
  margin-bottom: 8px;
}

.log-item-result {
  margin-top: 8px;
  padding: 8px;
  background-color: rgba(0, 0, 0, 0.03);
  border-radius: 4px;
  font-size: 12px;
  max-height: 200px;
  overflow-y: auto;
}

.dark .log-item-result {
  background-color: rgba(255, 255, 255, 0.05);
}
</style>
