// apps/frontend/src/views/system/timer/index.vue
<template>
  <div class="p-4">
    <NCard class="mb-4">
      <NForm inline :model="searchForm" label-placement="left" size="small">
        <NFormItem label="名称" path="name">
          <NInput v-model:value="searchForm.name" placeholder="输入任务名称" />
        </NFormItem>
        <NFormItem label="任务类型" path="taskType">
          <DictSelect
            dict-code="TASK_TYPE"
            v-model:value="searchForm.taskType"
            class="w-48!"
            placeholder="请选择"
          />
        </NFormItem>
        <NFormItem label="状态" path="status">
          <DictSelect
            dict-code="BASE_STATUS"
            v-model:value="searchForm.status"
            class="w-48!"
            placeholder="请选择"
          />
        </NFormItem>
        <NFormItem>
          <div class="flex gap-2">
            <NButton type="primary" @click="handleSearch">
              <template #icon>
                <AppIcon icon="antd:SearchOutlined" />
              </template>
              查询
            </NButton>
            <NButton @click="handleReset">
              <template #icon>
                <AppIcon icon="antd:ReloadOutlined" />
              </template>
              重置
            </NButton>
          </div>
        </NFormItem>
      </NForm>
    </NCard>

    <NCard>
      <div class="flex justify-between items-center mb-4">
        <n-space>
          <NButton type="primary" size="small" @click="openDialog()" v-permission="['TIMER_ADD']">
            <template #icon>
              <AppIcon icon="antd:PlusOutlined" />
            </template>
            新增定时任务
          </NButton>
        </n-space>
      </div>

      <NDataTable
        :columns="columns"
        :data="timerList"
        :loading="isLoading"
        :pagination="pagination"
        remote
        :row-key="getRowKey"
      />
    </NCard>

    <TimerDialog ref="dialogRef" @success="refetch" />
    <TimerLogsDrawer ref="logsDrawerRef" />
  </div>
</template>

<script setup lang="ts">
import { useQuery, useMutation } from '@pinia/colada'
import {
  getTimerList,
  deleteTimer,
  runTimer,
  type Timer,
  type TimerSearchParams,
} from '@/api/timer'
import TimerDialog from './TimerDialog.vue'
import TimerLogsDrawer from './TimerLogsDrawer.vue'
import { useDialog, useMessage } from 'naive-ui'
import { NTag, NTooltip, NButton, type DataTableColumns, type PaginationProps } from 'naive-ui'
import DynamicIcon from '@/components/Icon/DynamicIcon.vue'
import { usePermission } from '@/composables/usePermission'

defineOptions({
  name: 'SystemTimer',
})

const dialog = useDialog()
const message = useMessage()
const { hasPermission } = usePermission()

const dialogRef = ref()
const logsDrawerRef = ref()

const searchForm = reactive<TimerSearchParams>({
  name: '',
  taskType: undefined,
  status: undefined,
  pageNo: 1,
  pageSize: 10,
})
const createQueryState = () => ({ ...searchForm })
const queryState = ref(createQueryState())

const { data, isLoading, refetch } = useQuery({
  key: () => ['timers', queryState.value],
  query: () => getTimerList(queryState.value),
})

const timerList = computed(() => data.value?.data.list || [])
const total = computed(() => data.value?.data.total || 0)

const deleteMutation = useMutation({
  mutation: (id: number) => deleteTimer(id),
  onSuccess: () => {
    message.success('删除成功')
    refetch()
  },
  onError: () => {
    message.error('删除失败')
  },
})

const runMutation = useMutation({
  mutation: (id: number) => runTimer(id),
  onSuccess: () => {
    message.success('执行已触发')
  },
  onError: () => {
    message.error('触发执行失败')
  },
})

const pagination = reactive<PaginationProps>({
  page: 1,
  pageSize: 10,
  get itemCount() {
    return total.value
  },
  showSizePicker: true,
  pageSizes: [10, 20, 30],
  prefix: ({ itemCount }) => `共 ${itemCount} 条`,
  onChange: (page: number) => {
    pagination.page = page
    searchForm.pageNo = page
    queryState.value = createQueryState()
  },
  onUpdatePageSize: (pageSize: number) => {
    pagination.pageSize = pageSize
    pagination.page = 1
    searchForm.pageSize = pageSize
    searchForm.pageNo = 1
    queryState.value = createQueryState()
  },
})

const columns: DataTableColumns<Timer> = [
  { title: 'ID', key: 'id', width: 80 },
  { title: '名称', key: 'name' },
  { title: '描述', key: 'description', ellipsis: { tooltip: true } },
  {
    title: 'Cron 表达式',
    key: 'cron',
    render(row) {
      return h(NTag, { type: 'info', size: 'small' }, { default: () => row.cron })
    },
  },
  {
    title: '任务类型',
    key: 'taskType',
    render(row) {
      const type = row.taskType === 'HTTP' ? 'default' : 'warning'
      return h(NTag, { type, size: 'small' }, { default: () => row.taskType })
    },
  },
  {
    title: '目标',
    key: 'target',
    ellipsis: { tooltip: true },
    render(row) {
      return h('span', { class: 'text-xs' }, row.target)
    },
  },
  {
    title: '状态',
    key: 'status',
    render(row) {
      const type = row.status === 1 ? 'success' : 'default'
      const label = row.status === 1 ? '启用' : '禁用'
      return h(NTag, { type, size: 'small' }, { default: () => label })
    },
  },
  {
    title: '上次执行',
    key: 'lastRunAt',
    render(row) {
      return row.lastRunAt ? new Date(row.lastRunAt).toLocaleString() : '-'
    },
  },
  {
    title: '创建时间',
    key: 'createdAt',
    render(row) {
      return row.createdAt ? new Date(row.createdAt).toLocaleString() : '-'
    },
  },
  {
    title: '操作',
    key: 'actions',
    width: 200,
    fixed: 'right',
    render(row) {
      const actions = []

      if (hasPermission('TIMER_RUN')) {
        actions.push(
          h(
            NTooltip,
            {},
            {
              trigger: () =>
                h(
                  NButton,
                  {
                    type: 'info',
                    text: true,
                    size: 'small',
                    onClick: () => handleRun(row),
                  },
                  { icon: () => h(DynamicIcon, { icon: 'antd:PlayCircleOutlined' }) },
                ),
              default: () => '执行',
            },
          ),
        )
      }

      if (hasPermission('TIMER_LOG')) {
        actions.push(
          h(
            NTooltip,
            {},
            {
              trigger: () =>
                h(
                  NButton,
                  {
                    type: 'warning',
                    text: true,
                    size: 'small',
                    onClick: () => openLogs(row),
                  },
                  { icon: () => h(DynamicIcon, { icon: 'antd:UnorderedListOutlined' }) },
                ),
              default: () => '日志',
            },
          ),
        )
      }

      if (hasPermission('TIMER_EDIT')) {
        actions.push(
          h(
            NTooltip,
            {},
            {
              trigger: () =>
                h(
                  NButton,
                  {
                    type: 'success',
                    text: true,
                    size: 'small',
                    onClick: () => openDialog(row.id),
                  },
                  { icon: () => h(DynamicIcon, { icon: 'antd:EditOutlined' }) },
                ),
              default: () => '编辑',
            },
          ),
        )
      }

      if (hasPermission('TIMER_DELETE')) {
        actions.push(
          h(
            NTooltip,
            {},
            {
              trigger: () =>
                h(
                  NButton,
                  {
                    type: 'error',
                    text: true,
                    size: 'small',
                    onClick: () => confirmDelete(row),
                  },
                  { icon: () => h(DynamicIcon, { icon: 'antd:DeleteOutlined' }) },
                ),
              default: () => '删除',
            },
          ),
        )
      }

      return h('div', { class: 'flex gap-2' }, actions)
    },
  },
]

const getRowKey = (row: Timer) => row.id

const handleSearch = () => {
  searchForm.pageNo = 1
  pagination.page = 1
  queryState.value = createQueryState()
}

const handleReset = () => {
  searchForm.name = ''
  searchForm.taskType = undefined
  searchForm.status = undefined
  searchForm.pageNo = 1
  searchForm.pageSize = 10
  pagination.page = 1
  pagination.pageSize = 10
  queryState.value = createQueryState()
}

const openDialog = (id?: number) => {
  dialogRef.value?.open(id)
}

const openLogs = (timer: Timer) => {
  logsDrawerRef.value?.open(timer.id, timer.name)
}

const handleRun = (timer: Timer) => {
  dialog.info({
    title: '确认执行',
    content: `确定要手动执行定时任务 "${timer.name}" 吗？`,
    positiveText: '执行',
    negativeText: '取消',
    onPositiveClick: () => {
      runMutation.mutate(timer.id)
    },
  })
}

const confirmDelete = (timer: Timer) => {
  dialog.warning({
    title: '确认删除',
    content: `确定要删除定时任务 "${timer.name}" 吗？`,
    positiveText: '删除',
    negativeText: '取消',
    onPositiveClick: () => {
      deleteMutation.mutate(timer.id)
    },
  })
}
</script>

// apps/react-admin/src/pages/system/timer/index.tsx
import { useMemo, useState } from 'react'
import { useMutation, useQuery } from '@tanstack/react-query'
import { App, Button, Card, Form, Input, Popconfirm, Space, Table, Tag } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import {
  DeleteOutlined,
  EditOutlined,
  PlayCircleOutlined,
  PlusOutlined,
  ReloadOutlined,
  SearchOutlined,
  UnorderedListOutlined,
} from '@ant-design/icons'
import {
  deleteTimer,
  getTimerList,
  runTimer,
  type Timer,
  type TimerSearchParams,
} from '@/api/timer'
import { DictSelect } from '@/components/dict/DictSelect'
import { DictTag } from '@/components/dict/DictTag'
import { PermissionGate } from '@/components/PermissionGate'
import { TimerDialog } from '@/components/system/timer/TimerDialog'
import { TimerLogsDrawer } from '@/components/system/timer/TimerLogsDrawer'
import { queryClient } from '@/lib/query-client'

function formatDateTime(value?: string) {
  if (!value) return '-'
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return value
  return new Intl.DateTimeFormat('zh-CN', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: false,
  }).format(date)
}

export function TimerPage() {
  const { message } = App.useApp()
  const [form] = Form.useForm<TimerSearchParams>()
  const [query, setQuery] = useState<TimerSearchParams>({
    name: '',
    taskType: undefined,
    status: undefined,
    pageNo: 1,
    pageSize: 10,
  })
  const [dialogOpen, setDialogOpen] = useState(false)
  const [editingTimerId, setEditingTimerId] = useState<number | null>(null)
  const [logsDrawer, setLogsDrawer] = useState<{ open: boolean; id: number | null; name: string }>({
    open: false,
    id: null,
    name: '',
  })

  const { data, isLoading } = useQuery({
    queryKey: ['timers', query],
    queryFn: () => getTimerList(query),
  })

  const deleteMutation = useMutation({
    mutationFn: deleteTimer,
    onSuccess: async () => {
      message.success('删除成功')
      await queryClient.invalidateQueries({ queryKey: ['timers'] })
    },
    onError: () => {
      message.error('删除失败')
    },
  })

  const runMutation = useMutation({
    mutationFn: runTimer,
    onSuccess: () => {
      message.success('执行已触发')
    },
    onError: () => {
      message.error('触发执行失败')
    },
  })

  const columns = useMemo<ColumnsType<Timer>>(
    () => [
      { title: 'ID', dataIndex: 'id', key: 'id', width: 80 },
      { title: '名称', dataIndex: 'name', key: 'name', width: 180 },
      {
        title: '描述',
        dataIndex: 'description',
        key: 'description',
        ellipsis: true,
        render: (value: string | null | undefined) => value || '-',
      },
      {
        title: 'Cron 表达式',
        dataIndex: 'cron',
        key: 'cron',
        width: 180,
        render: (value: string) => <Tag color="blue">{value}</Tag>,
      },
      {
        title: '任务类型',
        dataIndex: 'taskType',
        key: 'taskType',
        width: 120,
        render: (value: string) => <DictTag value={value} dictCode="TASK_TYPE" />,
      },
      {
        title: '目标',
        dataIndex: 'target',
        key: 'target',
        ellipsis: true,
        render: (value: string) => <span className="text-xs">{value}</span>,
      },
      {
        title: '状态',
        dataIndex: 'status',
        key: 'status',
        width: 100,
        render: (value: number) => <DictTag value={value} dictCode="BASE_STATUS" />,
      },
      {
        title: '上次执行',
        dataIndex: 'lastRunAt',
        key: 'lastRunAt',
        width: 180,
        render: (value: string | undefined) => formatDateTime(value),
      },
      {
        title: '创建时间',
        dataIndex: 'createdAt',
        key: 'createdAt',
        width: 180,
        render: (value: string | undefined) => formatDateTime(value),
      },
      {
        title: '操作',
        key: 'actions',
        width: 180,
        render: (_, record) => (
          <Space size={4}>
            <PermissionGate permCode="TIMER_RUN">
              <Button
                type="text"
                size="small"
                icon={<PlayCircleOutlined />}
                onClick={() => {
                  void runMutation.mutateAsync(record.id)
                }}
              />
            </PermissionGate>
            <PermissionGate permCode="TIMER_LOG">
              <Button
                type="text"
                size="small"
                icon={<UnorderedListOutlined />}
                onClick={() => {
                  setLogsDrawer({
                    open: true,
                    id: record.id,
                    name: record.name,
                  })
                }}
              />
            </PermissionGate>
            <PermissionGate permCode="TIMER_EDIT">
              <Button
                type="text"
                size="small"
                icon={<EditOutlined />}
                onClick={() => {
                  setEditingTimerId(record.id)
                  setDialogOpen(true)
                }}
              />
            </PermissionGate>
            <PermissionGate permCode="TIMER_DELETE">
              <Popconfirm
                title="确认删除定时任务"
                description={`确定删除定时任务“${record.name}”吗？`}
                okText="删除"
                cancelText="取消"
                onConfirm={() => {
                  void deleteMutation.mutateAsync(record.id)
                }}
              >
                <Button danger type="text" size="small" icon={<DeleteOutlined />} />
              </Popconfirm>
            </PermissionGate>
          </Space>
        ),
      },
    ],
    [deleteMutation, runMutation],
  )

  return (
    <Space direction="vertical" size={16} style={{ display: 'flex' }}>
      <Card>
        <Form
          form={form}
          layout="inline"
          initialValues={{ name: '', taskType: undefined, status: undefined }}
        >
          <Form.Item label="名称" name="name">
            <Input allowClear placeholder="输入任务名称" style={{ width: 180 }} />
          </Form.Item>
          <Form.Item label="任务类型" name="taskType">
            <DictSelect dictCode="TASK_TYPE" style={{ width: 180 }} />
          </Form.Item>
          <Form.Item label="状态" name="status">
            <DictSelect dictCode="BASE_STATUS" style={{ width: 180 }} />
          </Form.Item>
          <Form.Item>
            <Space>
              <Button
                type="primary"
                icon={<SearchOutlined />}
                onClick={() => {
                  const values = form.getFieldsValue()
                  setQuery({
                    name: values.name?.trim() || '',
                    taskType: values.taskType,
                    status: values.status,
                    pageNo: 1,
                    pageSize: query.pageSize ?? 10,
                  })
                }}
              >
                查询
              </Button>
              <Button
                icon={<ReloadOutlined />}
                onClick={() => {
                  form.resetFields()
                  setQuery({
                    name: '',
                    taskType: undefined,
                    status: undefined,
                    pageNo: 1,
                    pageSize: 10,
                  })
                }}
              >
                重置
              </Button>
            </Space>
          </Form.Item>
        </Form>
      </Card>

      <Card>
        <Space direction="vertical" size={16} style={{ display: 'flex' }}>
          <PermissionGate permCode="TIMER_ADD">
            <Button
              type="primary"
              icon={<PlusOutlined />}
              onClick={() => {
                setEditingTimerId(null)
                setDialogOpen(true)
              }}
            >
              新增定时任务
            </Button>
          </PermissionGate>

          <Table<Timer>
            rowKey="id"
            loading={isLoading}
            columns={columns}
            dataSource={data?.list ?? []}
            scroll={{ x: 1400 }}
            pagination={{
              current: query.pageNo,
              pageSize: query.pageSize,
              total: data?.total ?? 0,
              showSizeChanger: true,
              pageSizeOptions: [10, 20, 30],
              showTotal: (total) => `共 ${total} 条`,
              onChange: (page, pageSize) => {
                setQuery((current) => ({
                  ...current,
                  pageNo: page,
                  pageSize,
                }))
              },
            }}
          />
        </Space>
      </Card>

      <TimerDialog
        open={dialogOpen}
        timerId={editingTimerId}
        onClose={() => {
          setDialogOpen(false)
          setEditingTimerId(null)
        }}
      />

      <TimerLogsDrawer
        open={logsDrawer.open}
        timerId={logsDrawer.id}
        timerName={logsDrawer.name}
        onClose={() => {
          setLogsDrawer({
            open: false,
            id: null,
            name: '',
          })
        }}
      />
    </Space>
  )
}
