// apps/frontend/src/views/system/menu/ButtonManageDialog.vue
<template>
  <NModal
    :show="show"
    :title="dialogTitle"
    preset="card"
    class="w-full md:w-220!"
    @update:show="close"
  >
    <NCard class="mb-4">
      <NForm inline :model="searchForm" label-placement="left" size="small">
        <NFormItem label="按钮名称" path="permName">
          <NInput v-model:value="searchForm.permName" placeholder="输入按钮名称" />
        </NFormItem>
        <NFormItem label="按钮编码" path="permCode">
          <NInput v-model:value="searchForm.permCode" placeholder="输入按钮编码" />
        </NFormItem>
        <NFormItem>
          <div class="flex gap-2">
            <NButton type="primary" @click="handleSearch">
              <template #icon>
                <AppIcon icon="antd:SearchOutlined" />
              </template>
              查询
            </NButton>
            <NButton @click="handleReset">
              <template #icon>
                <AppIcon icon="antd:ReloadOutlined" />
              </template>
              重置
            </NButton>
          </div>
        </NFormItem>
      </NForm>
    </NCard>

    <NCard>
      <div class="flex justify-between items-center mb-4">
        <NButton
          v-if="hasPermission('MENU_ADD')"
          type="primary"
          size="small"
          @click="openButtonForm()"
        >
          <template #icon>
            <AppIcon icon="antd:PlusOutlined" />
          </template>
          新增按钮
        </NButton>
      </div>

      <NDataTable
        size="small"
        :columns="columns"
        :data="buttonList"
        :loading="loading"
        :pagination="pagination"
        remote
        :row-key="getRowKey"
      />
    </NCard>

    <ButtonFormDialog ref="buttonFormDialogRef" @success="handleFormSuccess" />

    <template #footer>
      <div class="flex justify-end">
        <NButton @click="close">关闭</NButton>
      </div>
    </template>
  </NModal>
</template>

<script setup lang="ts">
import { computed, h, reactive, ref } from 'vue'
import dayjs from 'dayjs'
import {
  NModal,
  NCard,
  NForm,
  NFormItem,
  NInput,
  NButton,
  NDataTable,
  useDialog,
  useMessage,
  type DataTableColumns,
  type PaginationProps,
} from 'naive-ui'
import { deleteMenu, getButtonPermissionPage, type Menu } from '@/api/menu'
import { usePermission } from '@/composables/usePermission'
import DictTag from '@/components/Dict/DictTag.vue'
import DynamicIcon from '@/components/Icon/DynamicIcon.vue'
import ButtonFormDialog from './ButtonFormDialog.vue'

const emit = defineEmits<{
  (e: 'success'): void
}>()

const message = useMessage()
const dialog = useDialog()
const { hasPermission } = usePermission()

const show = ref(false)
const loading = ref(false)
const parentId = ref<number>()
const parentName = ref('')
const buttonList = ref<Menu[]>([])
const total = ref(0)
const buttonFormDialogRef = ref()

const searchForm = reactive({
  permName: '',
  permCode: '',
  pageNo: 1,
  pageSize: 10,
})

const dialogTitle = computed(() =>
  parentName.value ? `按钮管理 - ${parentName.value}` : '按钮管理',
)

const pagination = reactive<PaginationProps>({
  page: 1,
  pageSize: 10,
  get itemCount() {
    return total.value
  },
  showSizePicker: true,
  pageSizes: [10, 20, 30],
  onChange: (page: number) => {
    pagination.page = page
    searchForm.pageNo = page
    fetchList()
  },
  onUpdatePageSize: (pageSize: number) => {
    pagination.pageSize = pageSize
    pagination.page = 1
    searchForm.pageSize = pageSize
    searchForm.pageNo = 1
    fetchList()
  },
})

const columns: DataTableColumns<Menu> = [
  { title: '按钮名称', key: 'permName' },
  { title: '按钮编码', key: 'permCode' },
  {
    title: '状态',
    key: 'status',
    render(row) {
      return h(DictTag, { value: row.status, dictCode: 'BASE_STATUS' })
    },
  },
  { title: '排序', key: 'sort', width: 80 },
  {
    title: '创建时间',
    key: 'createdAt',
    render(row) {
      const createdAt = row.createdAt || row.createTime
      return createdAt ? dayjs(createdAt).format('YYYY-MM-DD HH:mm:ss') : '-'
    },
  },
  {
    title: '操作',
    key: 'actions',
    width: 120,
    render(row) {
      const actions = []

      if (hasPermission('MENU_EDIT')) {
        actions.push(
          h(
            NButton,
            {
              type: 'success',
              text: true,
              size: 'small',
              onClick: () => openButtonForm(row.id),
            },
            { icon: () => h(DynamicIcon, { icon: 'antd:EditOutlined' }) },
          ),
        )
      }

      if (hasPermission('MENU_DELETE')) {
        actions.push(
          h(
            NButton,
            {
              type: 'error',
              text: true,
              size: 'small',
              onClick: () => confirmDelete(row),
            },
            { icon: () => h(DynamicIcon, { icon: 'antd:DeleteOutlined' }) },
          ),
        )
      }

      return h('div', { class: 'flex gap-2' }, actions)
    },
  },
]

const getRowKey = (row: Menu) => row.id

const fetchList = async () => {
  if (!parentId.value) return
  loading.value = true
  try {
    const res = await getButtonPermissionPage({
      parentId: parentId.value,
      pageNo: searchForm.pageNo,
      pageSize: searchForm.pageSize,
      permName: searchForm.permName || undefined,
      permCode: searchForm.permCode || undefined,
    })
    buttonList.value = res.data?.list || []
    total.value = res.data?.total || 0
  } catch (error) {
    console.error(error)
  } finally {
    loading.value = false
  }
}

const open = async (menuId: number, menuName: string) => {
  parentId.value = menuId
  parentName.value = menuName
  searchForm.permName = ''
  searchForm.permCode = ''
  searchForm.pageNo = 1
  searchForm.pageSize = 10
  pagination.page = 1
  pagination.pageSize = 10
  show.value = true
  await fetchList()
}

const openButtonForm = (id?: number) => {
  if (!parentId.value) return
  buttonFormDialogRef.value?.open(parentId.value, id)
}

const handleSearch = () => {
  searchForm.pageNo = 1
  pagination.page = 1
  fetchList()
}

const handleReset = () => {
  searchForm.permName = ''
  searchForm.permCode = ''
  searchForm.pageNo = 1
  searchForm.pageSize = 10
  pagination.page = 1
  pagination.pageSize = 10
  fetchList()
}

const handleFormSuccess = async () => {
  emit('success')
  await fetchList()
}

const confirmDelete = (menu: Menu) => {
  dialog.warning({
    title: 'Confirm Delete',
    content: `Are you sure you want to delete "${menu.permName}"?`,
    positiveText: 'Delete',
    negativeText: 'Cancel',
    onPositiveClick: async () => {
      try {
        await deleteMenu(menu.id)
        message.success('Button deleted')
        emit('success')
        await fetchList()
      } catch (error) {
        console.error(error)
      }
    },
  })
}

const close = () => {
  show.value = false
}

defineExpose({
  open,
  close,
})
</script>

// apps/react-admin/src/components/system/menu/ButtonManageDialog.tsx
import { useMemo, useState } from 'react'
import { useMutation, useQuery } from '@tanstack/react-query'
import { App, Button, Card, Drawer, Form, Input, Popconfirm, Space, Table } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { DeleteOutlined, EditOutlined, PlusOutlined, ReloadOutlined, SearchOutlined } from '@ant-design/icons'
import { deleteMenu, getButtonPermissionPage, type Menu } from '@/api/menu'
import { DictTag } from '@/components/dict/DictTag'
import { PermissionGate } from '@/components/PermissionGate'
import { ButtonFormDialog } from '@/components/system/menu/ButtonFormDialog'
import { queryClient } from '@/lib/query-client'

function formatDateTime(value?: string) {
  if (!value) {
    return '-'
  }

  const date = new Date(value)
  if (Number.isNaN(date.getTime())) {
    return value
  }

  return new Intl.DateTimeFormat('zh-CN', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: false,
  }).format(date)
}

type Props = {
  open: boolean
  menuId?: number | null
  menuName?: string
  onClose: () => void
}

export function ButtonManageDialog({ open, menuId, menuName, onClose }: Props) {
  const { message } = App.useApp()
  const [form] = Form.useForm<{ permName?: string; permCode?: string }>()
  const [query, setQuery] = useState({
    permName: '',
    permCode: '',
    pageNo: 1,
    pageSize: 10,
  })
  const [buttonFormOpen, setButtonFormOpen] = useState(false)
  const [editingButtonId, setEditingButtonId] = useState<number | null>(null)

  const { data, isLoading } = useQuery({
    queryKey: ['menu-buttons', menuId, query],
    queryFn: () =>
      getButtonPermissionPage({
        parentId: menuId!,
        pageNo: query.pageNo,
        pageSize: query.pageSize,
        permName: query.permName || undefined,
        permCode: query.permCode || undefined,
      }),
    enabled: open && Boolean(menuId),
  })

  const deleteMutation = useMutation({
    mutationFn: deleteMenu,
    onSuccess: async () => {
      message.success('按钮删除成功')
      await queryClient.invalidateQueries({ queryKey: ['menu-buttons', menuId] })
      await queryClient.invalidateQueries({ queryKey: ['menus'] })
    },
  })

  const columns = useMemo<ColumnsType<Menu>>(
    () => [
      { title: '按钮名称', dataIndex: 'permName', key: 'permName' },
      { title: '按钮编码', dataIndex: 'permCode', key: 'permCode' },
      {
        title: '状态',
        dataIndex: 'status',
        key: 'status',
        width: 100,
        render: (value: number) => <DictTag value={value} dictCode="BASE_STATUS" />,
      },
      { title: '排序', dataIndex: 'sort', key: 'sort', width: 80 },
      {
        title: '创建时间',
        key: 'createdAt',
        width: 180,
        render: (_, record) => {
          const value = record.createdAt || record.createTime
          return formatDateTime(value)
        },
      },
      {
        title: '操作',
        key: 'actions',
        width: 120,
        render: (_, record) => (
          <Space size={4}>
            <PermissionGate permCode="MENU_EDIT">
              <Button
                type="text"
                size="small"
                icon={<EditOutlined />}
                onClick={() => {
                  setEditingButtonId(record.id)
                  setButtonFormOpen(true)
                }}
              />
            </PermissionGate>
            <PermissionGate permCode="MENU_DELETE">
              <Popconfirm
                title="确认删除按钮"
                description={`确定删除“${record.permName}”吗？`}
                okText="删除"
                cancelText="取消"
                onConfirm={() => {
                  void deleteMutation.mutateAsync(record.id)
                }}
              >
                <Button danger type="text" size="small" icon={<DeleteOutlined />} />
              </Popconfirm>
            </PermissionGate>
          </Space>
        ),
      },
    ],
    [deleteMutation],
  )

  return (
    <>
      <Drawer
        open={open}
        width={900}
        title={menuName ? `按钮管理 - ${menuName}` : '按钮管理'}
        onClose={onClose}
      >
        <Space direction="vertical" size={16} style={{ display: 'flex' }}>
          <Card>
            <Form form={form} layout="inline" initialValues={{ permName: '', permCode: '' }}>
              <Form.Item label="按钮名称" name="permName">
                <Input allowClear placeholder="输入按钮名称" style={{ width: 180 }} />
              </Form.Item>
              <Form.Item label="按钮编码" name="permCode">
                <Input allowClear placeholder="输入按钮编码" style={{ width: 180 }} />
              </Form.Item>
              <Form.Item>
                <Space>
                  <Button
                    type="primary"
                    icon={<SearchOutlined />}
                    onClick={() => {
                      const values = form.getFieldsValue()
                      setQuery({
                        permName: values.permName?.trim() || '',
                        permCode: values.permCode?.trim() || '',
                        pageNo: 1,
                        pageSize: query.pageSize,
                      })
                    }}
                  >
                    查询
                  </Button>
                  <Button
                    icon={<ReloadOutlined />}
                    onClick={() => {
                      form.resetFields()
                      setQuery({
                        permName: '',
                        permCode: '',
                        pageNo: 1,
                        pageSize: 10,
                      })
                    }}
                  >
                    重置
                  </Button>
                </Space>
              </Form.Item>
            </Form>
          </Card>

          <Card>
            <Space direction="vertical" size={16} style={{ display: 'flex' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <PermissionGate permCode="MENU_ADD">
                  <Button
                    type="primary"
                    icon={<PlusOutlined />}
                    onClick={() => {
                      setEditingButtonId(null)
                      setButtonFormOpen(true)
                    }}
                  >
                    新增按钮
                  </Button>
                </PermissionGate>
              </div>

              <Table<Menu>
                rowKey="id"
                loading={isLoading}
                columns={columns}
                dataSource={data?.list ?? []}
                pagination={{
                  current: query.pageNo,
                  pageSize: query.pageSize,
                  total: data?.total ?? 0,
                  showSizeChanger: true,
                  pageSizeOptions: [10, 20, 30],
                  showTotal: (total) => `共 ${total} 条`,
                  onChange: (page, pageSize) => {
                    setQuery((current) => ({
                      ...current,
                      pageNo: page,
                      pageSize,
                    }))
                  },
                }}
              />
            </Space>
          </Card>
        </Space>
      </Drawer>

      {menuId ? (
        <ButtonFormDialog
          open={buttonFormOpen}
          menuId={menuId}
          buttonId={editingButtonId}
          onClose={() => {
            setButtonFormOpen(false)
            setEditingButtonId(null)
          }}
        />
      ) : null}
    </>
  )
}
