// apps/frontend/src/views/system/file/index.vue
<template>
  <div class="p-4">
    <NCard class="mb-4">
      <NForm inline :model="searchForm" label-placement="left" size="small">
        <NFormItem label="文件类型" path="fileType">
          <NInput v-model:value="searchForm.fileType" placeholder="输入文件类型" />
        </NFormItem>
        <NFormItem>
          <div class="flex gap-2">
            <NButton type="primary" @click="handleSearch">
              <template #icon>
                <AppIcon icon="antd:SearchOutlined" />
              </template>
              查询
            </NButton>
            <NButton @click="handleReset">
              <template #icon>
                <AppIcon icon="antd:ReloadOutlined" />
              </template>
              重置
            </NButton>
          </div>
        </NFormItem>
      </NForm>
    </NCard>

    <NCard>
      <NDataTable
        :columns="columns"
        :data="fileList"
        :loading="isLoading"
        :pagination="pagination"
        remote
        :row-key="getRowKey"
      />
    </NCard>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useQuery } from '@pinia/colada'
import { getFileList, type FileEntity, type FileSearchParams } from '@/api/file'
import { NTag, type DataTableColumns, type PaginationProps } from 'naive-ui'

defineOptions({
  name: 'SystemFile',
})

const searchForm = reactive<FileSearchParams>({
  fileType: '',
  pageNo: 1,
  pageSize: 10,
})
const createQueryState = () => ({ ...searchForm })
const queryState = ref(createQueryState())

const { data, isLoading } = useQuery({
  key: () => ['files', queryState.value],
  query: () => getFileList(queryState.value),
})

const fileList = computed(() => data.value?.data.list || [])
const total = computed(() => data.value?.data.total || 0)

const pagination = reactive<PaginationProps>({
  page: 1,
  pageSize: 10,
  get itemCount() {
    return total.value
  },
  showSizePicker: true,
  pageSizes: [10, 20, 30],
  prefix: ({ itemCount }) => `共 ${itemCount} 条`,
  onChange: (page: number) => {
    pagination.page = page
    searchForm.pageNo = page
    queryState.value = createQueryState()
  },
  onUpdatePageSize: (pageSize: number) => {
    pagination.pageSize = pageSize
    pagination.page = 1
    searchForm.pageSize = pageSize
    searchForm.pageNo = 1
    queryState.value = createQueryState()
  },
})

// Format file size to human readable format
const formatFileSize = (bytes: number): string => {
  if (bytes === 0) return '0 B'
  const k = 1024
  const sizes = ['B', 'KB', 'MB', 'GB', 'TB']
  const i = Math.floor(Math.log(bytes) / Math.log(k))
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(2))} ${sizes[i]}`
}

const columns: DataTableColumns<FileEntity> = [
  { title: 'ID', key: 'id', width: 80 },
  { title: '文件名', key: 'filename' },
  {
    title: '原始名称',
    key: 'originalName',
    ellipsis: { tooltip: true },
  },
  {
    title: '大小',
    key: 'size',
    render(row) {
      return formatFileSize(row.size)
    },
  },
  { title: '类型', key: 'mimetype' },
  {
    title: '文件类型',
    key: 'fileType',
    render(row) {
      return h(NTag, { type: 'info', size: 'small' }, { default: () => row.fileType || '-' })
    },
  },
  {
    title: '公开',
    key: 'isPublic',
    render(row) {
      const type = row.isPublic ? 'success' : 'default'
      const label = row.isPublic ? '是' : '否'
      return h(NTag, { type, size: 'small' }, { default: () => label })
    },
  },
  {
    title: '创建时间',
    key: 'createdAt',
    render(row) {
      return row.createdAt ? new Date(row.createdAt).toLocaleString() : '-'
    },
  },
]

const getRowKey = (row: FileEntity) => row.id

const handleSearch = () => {
  searchForm.pageNo = 1
  pagination.page = 1
  queryState.value = createQueryState()
}

const handleReset = () => {
  searchForm.fileType = ''
  searchForm.isPublic = undefined
  searchForm.pageNo = 1
  searchForm.pageSize = 10
  pagination.page = 1
  pagination.pageSize = 10
  queryState.value = createQueryState()
}
</script>

// apps/react-admin/src/pages/system/file/index.tsx
import { useMemo, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { App, Button, Card, Form, Input, Space, Table, Tag } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { DownloadOutlined, EyeOutlined, ReloadOutlined, SearchOutlined } from '@ant-design/icons'
import { getFileList, type FileEntity, type FileSearchParams } from '@/api/file'

function formatDateTime(value?: string) {
  if (!value) return '-'
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return value
  return new Intl.DateTimeFormat('zh-CN', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: false,
  }).format(date)
}

function formatFileSize(bytes: number) {
  if (bytes === 0) return '0 B'
  const k = 1024
  const sizes = ['B', 'KB', 'MB', 'GB', 'TB']
  const i = Math.floor(Math.log(bytes) / Math.log(k))
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(2))} ${sizes[i]}`
}

export function FilePage() {
  const { message } = App.useApp()
  const [form] = Form.useForm<FileSearchParams>()
  const [query, setQuery] = useState<FileSearchParams>({
    fileType: '',
    isPublic: undefined,
    pageNo: 1,
    pageSize: 10,
  })

  const { data, isLoading } = useQuery({
    queryKey: ['files', query],
    queryFn: () => getFileList(query),
  })

  const columns = useMemo<ColumnsType<FileEntity>>(
    () => [
      { title: 'ID', dataIndex: 'id', key: 'id', width: 80 },
      { title: '文件名', dataIndex: 'filename', key: 'filename', width: 220 },
      {
        title: '原始名称',
        dataIndex: 'originalName',
        key: 'originalName',
        ellipsis: true,
      },
      {
        title: '大小',
        dataIndex: 'size',
        key: 'size',
        width: 120,
        render: (value: number) => formatFileSize(value),
      },
      { title: '类型', dataIndex: 'mimetype', key: 'mimetype', width: 180 },
      {
        title: '文件类型',
        dataIndex: 'fileType',
        key: 'fileType',
        width: 120,
        render: (value: string | undefined) => <Tag color="blue">{value || '-'}</Tag>,
      },
      {
        title: '公开',
        dataIndex: 'isPublic',
        key: 'isPublic',
        width: 100,
        render: (value: boolean | undefined) => (
          <Tag color={value ? 'success' : 'default'}>{value ? '是' : '否'}</Tag>
        ),
      },
      {
        title: '创建时间',
        dataIndex: 'createdAt',
        key: 'createdAt',
        width: 180,
        render: (value: string | undefined) => formatDateTime(value),
      },
      {
        title: '操作',
        key: 'actions',
        width: 120,
        render: (_, record) => (
          <Space size={4}>
            <Button
              type="text"
              size="small"
              icon={<EyeOutlined />}
              onClick={() => {
                if (!record.url) {
                  message.warning('当前文件没有可预览地址')
                  return
                }
                window.open(record.url, '_blank', 'noopener,noreferrer')
              }}
            />
            <Button
              type="text"
              size="small"
              icon={<DownloadOutlined />}
              onClick={() => {
                if (!record.url) {
                  message.warning('当前文件没有下载地址')
                  return
                }
                window.open(record.url, '_blank', 'noopener,noreferrer')
              }}
            />
          </Space>
        ),
      },
    ],
    [message],
  )

  return (
    <Space direction="vertical" size={16} style={{ display: 'flex' }}>
      <Card>
        <Form form={form} layout="inline" initialValues={{ fileType: '', isPublic: undefined }}>
          <Form.Item label="文件类型" name="fileType">
            <Input allowClear placeholder="输入文件类型" style={{ width: 180 }} />
          </Form.Item>
          <Form.Item>
            <Space>
              <Button
                type="primary"
                icon={<SearchOutlined />}
                onClick={() => {
                  const values = form.getFieldsValue()
                  setQuery({
                    fileType: values.fileType?.trim() || '',
                    isPublic: values.isPublic,
                    pageNo: 1,
                    pageSize: query.pageSize ?? 10,
                  })
                }}
              >
                查询
              </Button>
              <Button
                icon={<ReloadOutlined />}
                onClick={() => {
                  form.resetFields()
                  setQuery({
                    fileType: '',
                    isPublic: undefined,
                    pageNo: 1,
                    pageSize: 10,
                  })
                }}
              >
                重置
              </Button>
            </Space>
          </Form.Item>
        </Form>
      </Card>

      <Card>
        <Table<FileEntity>
          rowKey="id"
          loading={isLoading}
          columns={columns}
          dataSource={data?.list ?? []}
          scroll={{ x: 1300 }}
          pagination={{
            current: query.pageNo,
            pageSize: query.pageSize,
            total: data?.total ?? 0,
            showSizeChanger: true,
            pageSizeOptions: [10, 20, 30],
            showTotal: (total) => `共 ${total} 条`,
            onChange: (page, pageSize) => {
              setQuery((current) => ({
                ...current,
                pageNo: page,
                pageSize,
              }))
            },
          }}
        />
      </Card>
    </Space>
  )
}
