// apps/react-admin/src/pages/system/dictionary/index.tsx
import { useMemo, useState } from 'react'
import { useMutation, useQuery } from '@tanstack/react-query'
import { App, Button, Card, Form, Input, Popconfirm, Space, Table, Typography } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import {
  DeleteOutlined,
  EditOutlined,
  PlusOutlined,
  ReloadOutlined,
  SearchOutlined,
  UnorderedListOutlined,
} from '@ant-design/icons'
import {
  deleteDictionary,
  getDictionaryList,
  type Dictionary,
  type DictionarySearchParams,
} from '@/api/dictionary'
import { DictSelect } from '@/components/dict/DictSelect'
import { DictTag } from '@/components/dict/DictTag'
import { PermissionGate } from '@/components/PermissionGate'
import { DictionaryDialog } from '@/components/system/dictionary/DictionaryDialog'
import { DictionaryItemDrawer } from '@/components/system/dictionary/DictionaryItemDrawer'
import { queryClient } from '@/lib/query-client'

function formatDateTime(value?: string) {
  if (!value) {
    return '-'
  }

  const date = new Date(value)
  if (Number.isNaN(date.getTime())) {
    return value
  }

  return new Intl.DateTimeFormat('zh-CN', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: false,
  }).format(date)
}

export function DictionaryPage() {
  const { message } = App.useApp()
  const [form] = Form.useForm<DictionarySearchParams>()
  const [query, setQuery] = useState<DictionarySearchParams>({
    dictName: '',
    dictCode: '',
    status: undefined,
    pageNo: 1,
    pageSize: 10,
  })
  const [dialogOpen, setDialogOpen] = useState(false)
  const [editingDictionaryId, setEditingDictionaryId] = useState<number | null>(null)
  const [drawerState, setDrawerState] = useState<{
    open: boolean
    id: number | null
    name: string
  }>({
    open: false,
    id: null,
    name: '',
  })

  const { data, isLoading, isFetching } = useQuery({
    queryKey: ['dict-types', query],
    queryFn: () => getDictionaryList(query),
  })

  const deleteMutation = useMutation({
    mutationFn: deleteDictionary,
    onSuccess: async () => {
      message.success('字典删除成功')
      await queryClient.invalidateQueries({ queryKey: ['dict-types'] })
    },
  })

  const columns = useMemo<ColumnsType<Dictionary>>(
    () => [
      { title: '字典名称', dataIndex: 'dictName', key: 'dictName', width: 180 },
      { title: '字典编码', dataIndex: 'dictCode', key: 'dictCode', width: 180 },
      { title: '描述', dataIndex: 'description', key: 'description' },
      {
        title: '状态',
        dataIndex: 'status',
        key: 'status',
        width: 100,
        render: (value: number) => <DictTag value={value} dictCode="BASE_STATUS" />,
      },
      {
        title: '创建时间',
        dataIndex: 'createdAt',
        key: 'createdAt',
        width: 180,
        render: (value: string) => formatDateTime(value),
      },
      {
        title: '操作',
        key: 'actions',
        width: 220,
        render: (_, record) => (
          <Space size={4}>
            <PermissionGate permCode="DICT_ITEM">
              <Button
                type="text"
                size="small"
                icon={<UnorderedListOutlined />}
                onClick={() => {
                  setDrawerState({
                    open: true,
                    id: record.id,
                    name: record.dictName,
                  })
                }}
              >
                字典项
              </Button>
            </PermissionGate>
            <PermissionGate permCode="DICT_EDIT">
              <Button
                type="text"
                size="small"
                icon={<EditOutlined />}
                onClick={() => {
                  setEditingDictionaryId(record.id)
                  setDialogOpen(true)
                }}
              />
            </PermissionGate>
            <PermissionGate permCode="DICT_DELETE">
              <Popconfirm
                title="确认删除字典"
                description={`确定删除字典“${record.dictName}”吗？`}
                okText="删除"
                cancelText="取消"
                onConfirm={() => {
                  void deleteMutation.mutateAsync(record.id)
                }}
              >
                <Button danger type="text" size="small" icon={<DeleteOutlined />} />
              </Popconfirm>
            </PermissionGate>
          </Space>
        ),
      },
    ],
    [deleteMutation],
  )

  const handleSearch = () => {
    const values = form.getFieldsValue()
    setQuery({
      dictName: values.dictName?.trim() || '',
      dictCode: values.dictCode?.trim() || '',
      status: values.status,
      pageNo: 1,
      pageSize: query.pageSize ?? 10,
    })
  }

  const handleReset = () => {
    form.resetFields()
    setQuery({
      dictName: '',
      dictCode: '',
      status: undefined,
      pageNo: 1,
      pageSize: 10,
    })
  }

  return (
    <Space direction="vertical" size={16} style={{ display: 'flex' }}>
      <Card>
        <Form
          form={form}
          layout="inline"
          initialValues={{
            dictName: '',
            dictCode: '',
            status: undefined,
          }}
        >
          <Form.Item label="字典名称" name="dictName">
            <Input allowClear placeholder="输入字典名称" style={{ width: 180 }} />
          </Form.Item>
          <Form.Item label="字典编码" name="dictCode">
            <Input allowClear placeholder="输入字典编码" style={{ width: 180 }} />
          </Form.Item>
          <Form.Item label="状态" name="status">
            <DictSelect dictCode="BASE_STATUS" style={{ width: 180 }} />
          </Form.Item>
          <Form.Item>
            <Space>
              <Button type="primary" icon={<SearchOutlined />} onClick={handleSearch}>
                查询
              </Button>
              <Button icon={<ReloadOutlined />} onClick={handleReset}>
                重置
              </Button>
            </Space>
          </Form.Item>
        </Form>
      </Card>

      <Card>
        <Space direction="vertical" size={16} style={{ display: 'flex' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <Space>
              <Typography.Title level={5} style={{ margin: 0 }}>
                字典管理
              </Typography.Title>
              {isFetching ? <Typography.Text type="secondary">刷新中...</Typography.Text> : null}
            </Space>
            <PermissionGate permCode="DICT_ADD">
              <Button
                type="primary"
                icon={<PlusOutlined />}
                onClick={() => {
                  setEditingDictionaryId(null)
                  setDialogOpen(true)
                }}
              >
                新增字典
              </Button>
            </PermissionGate>
          </div>

          <Table<Dictionary>
            rowKey="id"
            loading={isLoading}
            columns={columns}
            dataSource={data?.list ?? []}
            scroll={{ x: 1200 }}
            pagination={{
              current: query.pageNo,
              pageSize: query.pageSize,
              total: data?.total ?? 0,
              showSizeChanger: true,
              pageSizeOptions: [10, 20, 30],
              showTotal: (total) => `共 ${total} 条`,
              onChange: (page, pageSize) => {
                setQuery((current) => ({
                  ...current,
                  pageNo: page,
                  pageSize,
                }))
              },
            }}
          />
        </Space>
      </Card>

      <DictionaryDialog
        open={dialogOpen}
        dictionaryId={editingDictionaryId}
        onClose={() => {
          setDialogOpen(false)
          setEditingDictionaryId(null)
        }}
      />
      <DictionaryItemDrawer
        open={drawerState.open}
        dictTypeId={drawerState.id}
        dictName={drawerState.name}
        onClose={() => {
          setDrawerState({
            open: false,
            id: null,
            name: '',
          })
        }}
      />
    </Space>
  )
}

// apps/frontend/src/views/system/dictionary/index.vue
<template>
  <div class="p-4">
    <NCard class="mb-4">
      <NForm inline :model="searchForm" label-placement="left" size="small">
        <NFormItem label="字典名称" path="dictName">
          <NInput v-model:value="searchForm.dictName" placeholder="Enter dict name" />
        </NFormItem>
        <NFormItem label="字典编码" path="dictCode">
          <NInput v-model:value="searchForm.dictCode" placeholder="Enter dict code" />
        </NFormItem>
        <NFormItem label="状态" path="status">
          <DictSelect dictCode="BASE_STATUS" v-model:value="searchForm.status" class="w-48!" />
        </NFormItem>
        <NFormItem>
          <div class="flex gap-2">
            <NButton type="primary" @click="handleSearch">
              <template #icon>
                <AppIcon icon="antd:SearchOutlined" />
              </template>
              查询
            </NButton>
            <NButton @click="handleReset">
              <template #icon>
                <AppIcon icon="antd:ReloadOutlined" />
              </template>
              重置
            </NButton>
          </div>
        </NFormItem>
      </NForm>
    </NCard>

    <NCard>
      <div class="flex justify-between items-center mb-4">
        <NSpace>
          <NButton type="primary" size="small" @click="openNew()" v-permission="['DICT_ADD']">
            <template #icon>
              <AppIcon icon="antd:PlusOutlined" />
            </template>
            新增字典
          </NButton>
        </NSpace>
      </div>

      <NDataTable
        size="small"
        :columns="columns"
        :data="dictList"
        :loading="isLoading"
        :pagination="pagination"
        remote
        :row-key="(row) => row.id"
      />
    </NCard>

    <DictionaryDialog ref="dialogRef" @success="refetch" />
    <DictionaryItemDrawer ref="drawerRef" />
  </div>
</template>

<script setup lang="ts">
import { ref, h, reactive, computed } from 'vue'
import { useQuery, useMutation } from '@pinia/colada'
import {
  getDictionaryList,
  deleteDictionary,
  type Dictionary,
  type DictionarySearchParams,
} from '@/api/dictionary'
import { useDialog, useMessage } from 'naive-ui'
import DictionaryDialog from './DictionaryDialog.vue'
import DictionaryItemDrawer from './components/DictionaryItemDrawer.vue'
import dayjs from 'dayjs'
import {
  NCard,
  NForm,
  NFormItem,
  NInput,
  NButton,
  NDataTable,
  NSpace,
  type DataTableColumns,
  type PaginationProps,
} from 'naive-ui'
import DictSelect from '@/components/Dict/DictSelect.vue'
import DictTag from '@/components/Dict/DictTag.vue'
import DynamicIcon from '@/components/Icon/DynamicIcon.vue'
import { usePermission } from '@/composables/usePermission'

defineOptions({
  name: 'SystemDictionary',
})

const dialog = useDialog()
const message = useMessage()
const { hasPermission } = usePermission()

const dialogRef = ref()
const drawerRef = ref()

const searchForm = reactive<DictionarySearchParams>({
  dictName: '',
  dictCode: '',
  status: undefined,
  pageNo: 1,
  pageSize: 10,
})
const createQueryState = () => ({ ...searchForm })
const queryState = ref(createQueryState())

const {
  data: queryData,
  isLoading,
  refetch,
} = useQuery({
  key: () => ['dictionaries', queryState.value],
  query: () => getDictionaryList(queryState.value),
})

const dictList = computed(() => queryData.value?.data?.list || [])
const total = computed(() => queryData.value?.data?.total || 0)

const deleteMutation = useMutation({
  mutation: (id: number) => deleteDictionary(id),
  onSuccess: () => {
    message.success('删除成功')
    refetch()
  },
})

const pagination = reactive<PaginationProps>({
  page: 1,
  pageSize: 10,
  get itemCount() {
    return total.value
  },
  showSizePicker: true,
  pageSizes: [10, 20, 30],
  onChange: (page: number) => {
    pagination.page = page
    searchForm.pageNo = page
    queryState.value = createQueryState()
  },
  onUpdatePageSize: (pageSize: number) => {
    pagination.pageSize = pageSize
    pagination.page = 1
    searchForm.pageSize = pageSize
    searchForm.pageNo = 1
    queryState.value = createQueryState()
  },
})

// Columns
const columns: DataTableColumns<Dictionary> = [
  { title: '字典名称', key: 'dictName' },
  { title: '字典编码', key: 'dictCode' },
  { title: '描述', key: 'description' },
  {
    title: '状态',
    key: 'status',
    render(row) {
      return h(DictTag, { value: row.status, dictCode: 'BASE_STATUS' })
    },
  },
  {
    title: '创建时间',
    key: 'createdAt',
    render(row) {
      return row.createdAt ? dayjs(row.createdAt).format('YYYY-MM-DD HH:mm:ss') : '-'
    },
  },
  {
    title: '操作',
    key: 'actions',
    width: 200,
    render(row) {
      const actions = []

      if (hasPermission('DICT_ITEM')) {
        actions.push(
          h(
            NButton,
            {
              type: 'info',
              text: true,
              size: 'small',
              onClick: () => openItems(row),
            },
            {
              icon: () => h(DynamicIcon, { icon: 'antd:UnorderedListOutlined' }),
              default: () => '字典项',
            },
          ),
        )
      }

      if (hasPermission('DICT_EDIT')) {
        actions.push(
          h(
            NButton,
            {
              type: 'success',
              text: true,
              size: 'small',
              onClick: () => editDict(row),
            },
            { icon: () => h(DynamicIcon, { icon: 'antd:EditOutlined' }) },
          ),
        )
      }

      if (hasPermission('DICT_DELETE')) {
        actions.push(
          h(
            NButton,
            {
              type: 'error',
              text: true,
              size: 'small',
              onClick: () => confirmDeleteDict(row),
            },
            { icon: () => h(DynamicIcon, { icon: 'antd:DeleteOutlined' }) },
          ),
        )
      }

      return h('div', { class: 'flex gap-2' }, actions)
    },
  },
]

const handleSearch = () => {
  searchForm.pageNo = 1
  pagination.page = 1
  queryState.value = createQueryState()
}

const handleReset = () => {
  searchForm.dictName = ''
  searchForm.dictCode = ''
  searchForm.status = undefined
  searchForm.pageNo = 1
  searchForm.pageSize = 10
  pagination.page = 1
  pagination.pageSize = 10
  queryState.value = createQueryState()
}

const openNew = () => {
  dialogRef.value?.open()
}

const editDict = (dict: Dictionary) => {
  dialogRef.value?.open(dict.id)
}

const confirmDeleteDict = (dict: Dictionary) => {
  dialog.warning({
    title: '确认删除',
    content: `确定要删除字典 "${dict.dictName}" 吗？`,
    positiveText: '删除',
    negativeText: '取消',
    onPositiveClick: () => {
      deleteMutation.mutate(dict.id)
    },
  })
}

const openItems = (dict: Dictionary) => {
  drawerRef.value?.open(dict.id)
}
</script>
